/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.voices;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * CreateVoiceRequest
 * 
 * <p>Request message for `VoicesService.CreateVoice`.
 */
public class CreateVoiceRequest {
    /**
     * Optional. Whether the created voice is persisted and managed by Google.
     * 
     * <p>* When `true`, Google stores the voice and returns `Voice.id` (for example,
     * `voice_abc123def456`), which can be managed via `GetVoice`, `ListVoices`,
     * and `DeleteVoice` and referenced by ID in synthesis requests. Stored
     * voices expire after 1 year of inactivity; using a stored voice in speech
     * synthesis or as a `base_voice` in `CreateVoice` extends its
     * `expire_time`. Projects are subject to a maximum active stored voice
     * quota; exceeding the quota returns `RESOURCE_EXHAUSTED`.
     * * When `false` (default), the voice is not stored by Google and `Voice.key`
     * (for example, `voicekey_...`) is returned for client-side storage and
     * synthesis. Optional discovery metadata fields on `voice` are not
     * persisted or returned when `store` is `false`.
     * * Required to be `true` when `voice.type` is `"prompted"`
     * (otherwise fails with `INVALID_ARGUMENT`).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("store")
    private Boolean store;

    /**
     * A voice resource representing either a custom voice (created via
     * `CreateVoice`) or a prebuilt system voice (returned by `ListVoices`).
     */
    @JsonProperty("voice")
    private VoiceInput voice;

    @JsonCreator
    public CreateVoiceRequest(
            @JsonProperty("store") @Nullable Boolean store,
            @JsonProperty("voice") @Nonnull VoiceInput voice) {
        this.store = store;
        this.voice = Optional.ofNullable(voice)
            .orElseThrow(() -> new IllegalArgumentException("voice cannot be null"));
    }
    
    public CreateVoiceRequest(
            @Nonnull VoiceInput voice) {
        this(null, voice);
    }

    /**
     * Optional. Whether the created voice is persisted and managed by Google.
     * 
     * <p>* When `true`, Google stores the voice and returns `Voice.id` (for example,
     * `voice_abc123def456`), which can be managed via `GetVoice`, `ListVoices`,
     * and `DeleteVoice` and referenced by ID in synthesis requests. Stored
     * voices expire after 1 year of inactivity; using a stored voice in speech
     * synthesis or as a `base_voice` in `CreateVoice` extends its
     * `expire_time`. Projects are subject to a maximum active stored voice
     * quota; exceeding the quota returns `RESOURCE_EXHAUSTED`.
     * * When `false` (default), the voice is not stored by Google and `Voice.key`
     * (for example, `voicekey_...`) is returned for client-side storage and
     * synthesis. Optional discovery metadata fields on `voice` are not
     * persisted or returned when `store` is `false`.
     * * Required to be `true` when `voice.type` is `"prompted"`
     * (otherwise fails with `INVALID_ARGUMENT`).
     */
    public Optional<Boolean> store() {
        return Optional.ofNullable(this.store);
    }

    /**
     * A voice resource representing either a custom voice (created via
     * `CreateVoice`) or a prebuilt system voice (returned by `ListVoices`).
     */
    public Optional<VoiceInput> voice() {
        return Optional.ofNullable(this.voice);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Optional. Whether the created voice is persisted and managed by Google.
     * 
     * <p>* When `true`, Google stores the voice and returns `Voice.id` (for example,
     * `voice_abc123def456`), which can be managed via `GetVoice`, `ListVoices`,
     * and `DeleteVoice` and referenced by ID in synthesis requests. Stored
     * voices expire after 1 year of inactivity; using a stored voice in speech
     * synthesis or as a `base_voice` in `CreateVoice` extends its
     * `expire_time`. Projects are subject to a maximum active stored voice
     * quota; exceeding the quota returns `RESOURCE_EXHAUSTED`.
     * * When `false` (default), the voice is not stored by Google and `Voice.key`
     * (for example, `voicekey_...`) is returned for client-side storage and
     * synthesis. Optional discovery metadata fields on `voice` are not
     * persisted or returned when `store` is `false`.
     * * Required to be `true` when `voice.type` is `"prompted"`
     * (otherwise fails with `INVALID_ARGUMENT`).
     */
    public CreateVoiceRequest withStore(@Nullable Boolean store) {
        this.store = store;
        return this;
    }


    /**
     * A voice resource representing either a custom voice (created via
     * `CreateVoice`) or a prebuilt system voice (returned by `ListVoices`).
     */
    public CreateVoiceRequest withVoice(@Nonnull VoiceInput voice) {
        this.voice = Utils.checkNotNull(voice, "voice");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateVoiceRequest other = (CreateVoiceRequest) o;
        return 
            Utils.enhancedDeepEquals(this.store, other.store) &&
            Utils.enhancedDeepEquals(this.voice, other.voice);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            store, voice);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateVoiceRequest.class,
                "store", store,
                "voice", voice);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Boolean store;

        private VoiceInput voice;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Optional. Whether the created voice is persisted and managed by Google.
         * 
         * <p>* When `true`, Google stores the voice and returns `Voice.id` (for example,
         * `voice_abc123def456`), which can be managed via `GetVoice`, `ListVoices`,
         * and `DeleteVoice` and referenced by ID in synthesis requests. Stored
         * voices expire after 1 year of inactivity; using a stored voice in speech
         * synthesis or as a `base_voice` in `CreateVoice` extends its
         * `expire_time`. Projects are subject to a maximum active stored voice
         * quota; exceeding the quota returns `RESOURCE_EXHAUSTED`.
         * * When `false` (default), the voice is not stored by Google and `Voice.key`
         * (for example, `voicekey_...`) is returned for client-side storage and
         * synthesis. Optional discovery metadata fields on `voice` are not
         * persisted or returned when `store` is `false`.
         * * Required to be `true` when `voice.type` is `"prompted"`
         * (otherwise fails with `INVALID_ARGUMENT`).
         */
        public Builder store(@Nullable Boolean store) {
            this.store = store;
            return this;
        }

        /**
         * A voice resource representing either a custom voice (created via
         * `CreateVoice`) or a prebuilt system voice (returned by `ListVoices`).
         */
        public Builder voice(@Nonnull VoiceInput voice) {
            this.voice = Utils.checkNotNull(voice, "voice");
            return this;
        }

        public CreateVoiceRequest build() {
            return new CreateVoiceRequest(
                store, voice);
        }

    }
}
