/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.voices;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.models.interactions.Usage;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

/**
 * VoiceOutput
 * 
 * <p>A voice resource representing either a custom voice (created via
 * `CreateVoice`) or a prebuilt system voice (returned by `ListVoices`).
 */
public class VoiceOutput {
    /**
     * Optional. Regional accent descriptor (e.g. "American", "British").
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("accent")
    private String accent;

    /**
     * Optional. Optimal usage context or domain (e.g. "Conversational",
     * "Audiobook", "News").
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("context")
    private String context;

    /**
     * Optional. Descriptive summary of vocal timbre, personality, and tone.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private String description;

    /**
     * Optional. User-provided display name for a stored voice (`store = true`),
     * or the catalog name for a prebuilt voice.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("display_name")
    private String displayName;

    /**
     * Output only. The timestamp at which a custom stored voice (`store = true`)
     * or replicated voice key (`store = false`) expires. For custom stored voices
     * (`store = true`), this expiration time is extended when the voice is used
     * for speech synthesis or as a `base_voice` in `CreateVoice`. Unset for
     * prebuilt catalog voices (`"prebuilt"`), which do not expire.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expire_time")
    private OffsetDateTime expireTime;

    /**
     * Optional. Perceived voice gender presentation (e.g. "female", "male",
     * "neutral").
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("gender")
    private String gender;

    /**
     * Output only. The unique identifier of the voice.
     * 
     * <p>* For Google-managed custom voices (`store = true`), this is a generated ID
     * with prefix `voice_` (for example, `voice_abc123def456`). Pass
     * `voices/{id}` as the `name` in `GetVoice` and `DeleteVoice`, and pass
     * `{id}` directly to `SpeechConfig.voice_config.voice` (or
     * `SpeechConfig.voice`) during speech synthesis.
     * * For prebuilt catalog voices (`"prebuilt"` returned by `ListVoices`), this
     * is the speaker name (for example, `Puck` or `Charon`).
     * * Unset when `CreateVoice` is called with `store = false`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    /**
     * Output only. The client-managed voice replication key (with prefix
     * `voicekey_`). Returned only by `CreateVoice` when `type` is `"replicated"`
     * and `store` is `false`. Pass this key to `SpeechConfig.voice_config.voice`
     * (or `SpeechConfig.voice`) during speech synthesis.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("key")
    private String key;

    /**
     * Optional. Primary BCP-47 language tag (e.g. "en-US", "fr-FR").
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("language_code")
    private String languageCode;

    /**
     * Optional. The model used to design or replicate the voice.
     * If omitted in `CreateVoice`, defaults to the latest supported voice design
     * model. Returned in `CreateVoice`, `GetVoice`, and `ListVoices` responses
     * for custom voices (`"prompted"` and `"replicated"`); unset for `"prebuilt"`
     * voices. Created voices can be synthesized across any supported TTS
     * synthesis model.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("model")
    private String model;

    /**
     * Optional. Intended persona or character archetype (e.g. "Warm, Friendly",
     * "Narrator").
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("persona")
    private String persona;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pitch")
    private Pitch pitch;

    /**
     * Parameters for prompted voice generation.
     * Required in `CreateVoice` when `type` is `"prompted"`. Returned in
     * `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prompted")
    private PromptedVoice prompted;

    /**
     * Optional. ISO 3166-1 alpha-2 or UN M.49 geographic region code (e.g. "US",
     * "GB", "001").
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("region_code")
    private String regionCode;

    /**
     * Audio payload used for voice creation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sample_audio")
    private AudioData sampleAudio;


    @JsonProperty("type")
    private VoiceType type;

    /**
     * Statistics on the interaction request's token usage.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("usage")
    private Usage usage;

    @JsonCreator
    public VoiceOutput(
            @JsonProperty("accent") @Nullable String accent,
            @JsonProperty("context") @Nullable String context,
            @JsonProperty("description") @Nullable String description,
            @JsonProperty("display_name") @Nullable String displayName,
            @JsonProperty("expire_time") @Nullable OffsetDateTime expireTime,
            @JsonProperty("gender") @Nullable String gender,
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("key") @Nullable String key,
            @JsonProperty("language_code") @Nullable String languageCode,
            @JsonProperty("model") @Nullable String model,
            @JsonProperty("persona") @Nullable String persona,
            @JsonProperty("pitch") @Nullable Pitch pitch,
            @JsonProperty("prompted") @Nullable PromptedVoice prompted,
            @JsonProperty("region_code") @Nullable String regionCode,
            @JsonProperty("sample_audio") @Nullable AudioData sampleAudio,
            @JsonProperty("type") @Nonnull VoiceType type,
            @JsonProperty("usage") @Nullable Usage usage) {
        this.accent = accent;
        this.context = context;
        this.description = description;
        this.displayName = displayName;
        this.expireTime = expireTime;
        this.gender = gender;
        this.id = id;
        this.key = key;
        this.languageCode = languageCode;
        this.model = model;
        this.persona = persona;
        this.pitch = pitch;
        this.prompted = prompted;
        this.regionCode = regionCode;
        this.sampleAudio = sampleAudio;
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.usage = usage;
    }
    
    public VoiceOutput(
            @Nonnull VoiceType type) {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            type, null);
    }

    /**
     * Optional. Regional accent descriptor (e.g. "American", "British").
     */
    public Optional<String> accent() {
        return Optional.ofNullable(this.accent);
    }

    /**
     * Optional. Optimal usage context or domain (e.g. "Conversational",
     * "Audiobook", "News").
     */
    public Optional<String> context() {
        return Optional.ofNullable(this.context);
    }

    /**
     * Optional. Descriptive summary of vocal timbre, personality, and tone.
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Optional. User-provided display name for a stored voice (`store = true`),
     * or the catalog name for a prebuilt voice.
     */
    public Optional<String> displayName() {
        return Optional.ofNullable(this.displayName);
    }

    /**
     * Output only. The timestamp at which a custom stored voice (`store = true`)
     * or replicated voice key (`store = false`) expires. For custom stored voices
     * (`store = true`), this expiration time is extended when the voice is used
     * for speech synthesis or as a `base_voice` in `CreateVoice`. Unset for
     * prebuilt catalog voices (`"prebuilt"`), which do not expire.
     */
    public Optional<OffsetDateTime> expireTime() {
        return Optional.ofNullable(this.expireTime);
    }

    /**
     * Optional. Perceived voice gender presentation (e.g. "female", "male",
     * "neutral").
     */
    public Optional<String> gender() {
        return Optional.ofNullable(this.gender);
    }

    /**
     * Output only. The unique identifier of the voice.
     * 
     * <p>* For Google-managed custom voices (`store = true`), this is a generated ID
     * with prefix `voice_` (for example, `voice_abc123def456`). Pass
     * `voices/{id}` as the `name` in `GetVoice` and `DeleteVoice`, and pass
     * `{id}` directly to `SpeechConfig.voice_config.voice` (or
     * `SpeechConfig.voice`) during speech synthesis.
     * * For prebuilt catalog voices (`"prebuilt"` returned by `ListVoices`), this
     * is the speaker name (for example, `Puck` or `Charon`).
     * * Unset when `CreateVoice` is called with `store = false`.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * Output only. The client-managed voice replication key (with prefix
     * `voicekey_`). Returned only by `CreateVoice` when `type` is `"replicated"`
     * and `store` is `false`. Pass this key to `SpeechConfig.voice_config.voice`
     * (or `SpeechConfig.voice`) during speech synthesis.
     */
    public Optional<String> key() {
        return Optional.ofNullable(this.key);
    }

    /**
     * Optional. Primary BCP-47 language tag (e.g. "en-US", "fr-FR").
     */
    public Optional<String> languageCode() {
        return Optional.ofNullable(this.languageCode);
    }

    /**
     * Optional. The model used to design or replicate the voice.
     * If omitted in `CreateVoice`, defaults to the latest supported voice design
     * model. Returned in `CreateVoice`, `GetVoice`, and `ListVoices` responses
     * for custom voices (`"prompted"` and `"replicated"`); unset for `"prebuilt"`
     * voices. Created voices can be synthesized across any supported TTS
     * synthesis model.
     */
    public Optional<String> model() {
        return Optional.ofNullable(this.model);
    }

    /**
     * Optional. Intended persona or character archetype (e.g. "Warm, Friendly",
     * "Narrator").
     */
    public Optional<String> persona() {
        return Optional.ofNullable(this.persona);
    }

    public Optional<Pitch> pitch() {
        return Optional.ofNullable(this.pitch);
    }

    /**
     * Parameters for prompted voice generation.
     * Required in `CreateVoice` when `type` is `"prompted"`. Returned in
     * `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
     */
    public Optional<PromptedVoice> prompted() {
        return Optional.ofNullable(this.prompted);
    }

    /**
     * Optional. ISO 3166-1 alpha-2 or UN M.49 geographic region code (e.g. "US",
     * "GB", "001").
     */
    public Optional<String> regionCode() {
        return Optional.ofNullable(this.regionCode);
    }

    /**
     * Audio payload used for voice creation.
     */
    public Optional<AudioData> sampleAudio() {
        return Optional.ofNullable(this.sampleAudio);
    }

    public Optional<VoiceType> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * Statistics on the interaction request's token usage.
     */
    public Optional<Usage> usage() {
        return Optional.ofNullable(this.usage);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Optional. Regional accent descriptor (e.g. "American", "British").
     */
    public VoiceOutput withAccent(@Nullable String accent) {
        this.accent = accent;
        return this;
    }


    /**
     * Optional. Optimal usage context or domain (e.g. "Conversational",
     * "Audiobook", "News").
     */
    public VoiceOutput withContext(@Nullable String context) {
        this.context = context;
        return this;
    }


    /**
     * Optional. Descriptive summary of vocal timbre, personality, and tone.
     */
    public VoiceOutput withDescription(@Nullable String description) {
        this.description = description;
        return this;
    }


    /**
     * Optional. User-provided display name for a stored voice (`store = true`),
     * or the catalog name for a prebuilt voice.
     */
    public VoiceOutput withDisplayName(@Nullable String displayName) {
        this.displayName = displayName;
        return this;
    }


    /**
     * Output only. The timestamp at which a custom stored voice (`store = true`)
     * or replicated voice key (`store = false`) expires. For custom stored voices
     * (`store = true`), this expiration time is extended when the voice is used
     * for speech synthesis or as a `base_voice` in `CreateVoice`. Unset for
     * prebuilt catalog voices (`"prebuilt"`), which do not expire.
     */
    public VoiceOutput withExpireTime(@Nullable OffsetDateTime expireTime) {
        this.expireTime = expireTime;
        return this;
    }


    /**
     * Optional. Perceived voice gender presentation (e.g. "female", "male",
     * "neutral").
     */
    public VoiceOutput withGender(@Nullable String gender) {
        this.gender = gender;
        return this;
    }


    /**
     * Output only. The unique identifier of the voice.
     * 
     * <p>* For Google-managed custom voices (`store = true`), this is a generated ID
     * with prefix `voice_` (for example, `voice_abc123def456`). Pass
     * `voices/{id}` as the `name` in `GetVoice` and `DeleteVoice`, and pass
     * `{id}` directly to `SpeechConfig.voice_config.voice` (or
     * `SpeechConfig.voice`) during speech synthesis.
     * * For prebuilt catalog voices (`"prebuilt"` returned by `ListVoices`), this
     * is the speaker name (for example, `Puck` or `Charon`).
     * * Unset when `CreateVoice` is called with `store = false`.
     */
    public VoiceOutput withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    /**
     * Output only. The client-managed voice replication key (with prefix
     * `voicekey_`). Returned only by `CreateVoice` when `type` is `"replicated"`
     * and `store` is `false`. Pass this key to `SpeechConfig.voice_config.voice`
     * (or `SpeechConfig.voice`) during speech synthesis.
     */
    public VoiceOutput withKey(@Nullable String key) {
        this.key = key;
        return this;
    }


    /**
     * Optional. Primary BCP-47 language tag (e.g. "en-US", "fr-FR").
     */
    public VoiceOutput withLanguageCode(@Nullable String languageCode) {
        this.languageCode = languageCode;
        return this;
    }


    /**
     * Optional. The model used to design or replicate the voice.
     * If omitted in `CreateVoice`, defaults to the latest supported voice design
     * model. Returned in `CreateVoice`, `GetVoice`, and `ListVoices` responses
     * for custom voices (`"prompted"` and `"replicated"`); unset for `"prebuilt"`
     * voices. Created voices can be synthesized across any supported TTS
     * synthesis model.
     */
    public VoiceOutput withModel(@Nullable String model) {
        this.model = model;
        return this;
    }


    /**
     * Optional. Intended persona or character archetype (e.g. "Warm, Friendly",
     * "Narrator").
     */
    public VoiceOutput withPersona(@Nullable String persona) {
        this.persona = persona;
        return this;
    }


    public VoiceOutput withPitch(@Nullable Pitch pitch) {
        this.pitch = pitch;
        return this;
    }


    /**
     * Parameters for prompted voice generation.
     * Required in `CreateVoice` when `type` is `"prompted"`. Returned in
     * `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
     */
    public VoiceOutput withPrompted(@Nullable PromptedVoice prompted) {
        this.prompted = prompted;
        return this;
    }


    /**
     * Optional. ISO 3166-1 alpha-2 or UN M.49 geographic region code (e.g. "US",
     * "GB", "001").
     */
    public VoiceOutput withRegionCode(@Nullable String regionCode) {
        this.regionCode = regionCode;
        return this;
    }


    /**
     * Audio payload used for voice creation.
     */
    public VoiceOutput withSampleAudio(@Nullable AudioData sampleAudio) {
        this.sampleAudio = sampleAudio;
        return this;
    }


    public VoiceOutput withType(@Nonnull VoiceType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    /**
     * Statistics on the interaction request's token usage.
     */
    public VoiceOutput withUsage(@Nullable Usage usage) {
        this.usage = usage;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VoiceOutput other = (VoiceOutput) o;
        return 
            Utils.enhancedDeepEquals(this.accent, other.accent) &&
            Utils.enhancedDeepEquals(this.context, other.context) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.displayName, other.displayName) &&
            Utils.enhancedDeepEquals(this.expireTime, other.expireTime) &&
            Utils.enhancedDeepEquals(this.gender, other.gender) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.key, other.key) &&
            Utils.enhancedDeepEquals(this.languageCode, other.languageCode) &&
            Utils.enhancedDeepEquals(this.model, other.model) &&
            Utils.enhancedDeepEquals(this.persona, other.persona) &&
            Utils.enhancedDeepEquals(this.pitch, other.pitch) &&
            Utils.enhancedDeepEquals(this.prompted, other.prompted) &&
            Utils.enhancedDeepEquals(this.regionCode, other.regionCode) &&
            Utils.enhancedDeepEquals(this.sampleAudio, other.sampleAudio) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.usage, other.usage);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accent, context, description,
            displayName, expireTime, gender,
            id, key, languageCode,
            model, persona, pitch,
            prompted, regionCode, sampleAudio,
            type, usage);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VoiceOutput.class,
                "accent", accent,
                "context", context,
                "description", description,
                "displayName", displayName,
                "expireTime", expireTime,
                "gender", gender,
                "id", id,
                "key", key,
                "languageCode", languageCode,
                "model", model,
                "persona", persona,
                "pitch", pitch,
                "prompted", prompted,
                "regionCode", regionCode,
                "sampleAudio", sampleAudio,
                "type", type,
                "usage", usage);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accent;

        private String context;

        private String description;

        private String displayName;

        private OffsetDateTime expireTime;

        private String gender;

        private String id;

        private String key;

        private String languageCode;

        private String model;

        private String persona;

        private Pitch pitch;

        private PromptedVoice prompted;

        private String regionCode;

        private AudioData sampleAudio;

        private VoiceType type;

        private Usage usage;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Optional. Regional accent descriptor (e.g. "American", "British").
         */
        public Builder accent(@Nullable String accent) {
            this.accent = accent;
            return this;
        }

        /**
         * Optional. Optimal usage context or domain (e.g. "Conversational",
         * "Audiobook", "News").
         */
        public Builder context(@Nullable String context) {
            this.context = context;
            return this;
        }

        /**
         * Optional. Descriptive summary of vocal timbre, personality, and tone.
         */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /**
         * Optional. User-provided display name for a stored voice (`store = true`),
         * or the catalog name for a prebuilt voice.
         */
        public Builder displayName(@Nullable String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Output only. The timestamp at which a custom stored voice (`store = true`)
         * or replicated voice key (`store = false`) expires. For custom stored voices
         * (`store = true`), this expiration time is extended when the voice is used
         * for speech synthesis or as a `base_voice` in `CreateVoice`. Unset for
         * prebuilt catalog voices (`"prebuilt"`), which do not expire.
         */
        public Builder expireTime(@Nullable OffsetDateTime expireTime) {
            this.expireTime = expireTime;
            return this;
        }

        /**
         * Optional. Perceived voice gender presentation (e.g. "female", "male",
         * "neutral").
         */
        public Builder gender(@Nullable String gender) {
            this.gender = gender;
            return this;
        }

        /**
         * Output only. The unique identifier of the voice.
         * 
         * <p>* For Google-managed custom voices (`store = true`), this is a generated ID
         * with prefix `voice_` (for example, `voice_abc123def456`). Pass
         * `voices/{id}` as the `name` in `GetVoice` and `DeleteVoice`, and pass
         * `{id}` directly to `SpeechConfig.voice_config.voice` (or
         * `SpeechConfig.voice`) during speech synthesis.
         * * For prebuilt catalog voices (`"prebuilt"` returned by `ListVoices`), this
         * is the speaker name (for example, `Puck` or `Charon`).
         * * Unset when `CreateVoice` is called with `store = false`.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /**
         * Output only. The client-managed voice replication key (with prefix
         * `voicekey_`). Returned only by `CreateVoice` when `type` is `"replicated"`
         * and `store` is `false`. Pass this key to `SpeechConfig.voice_config.voice`
         * (or `SpeechConfig.voice`) during speech synthesis.
         */
        public Builder key(@Nullable String key) {
            this.key = key;
            return this;
        }

        /**
         * Optional. Primary BCP-47 language tag (e.g. "en-US", "fr-FR").
         */
        public Builder languageCode(@Nullable String languageCode) {
            this.languageCode = languageCode;
            return this;
        }

        /**
         * Optional. The model used to design or replicate the voice.
         * If omitted in `CreateVoice`, defaults to the latest supported voice design
         * model. Returned in `CreateVoice`, `GetVoice`, and `ListVoices` responses
         * for custom voices (`"prompted"` and `"replicated"`); unset for `"prebuilt"`
         * voices. Created voices can be synthesized across any supported TTS
         * synthesis model.
         */
        public Builder model(@Nullable String model) {
            this.model = model;
            return this;
        }

        /**
         * Optional. Intended persona or character archetype (e.g. "Warm, Friendly",
         * "Narrator").
         */
        public Builder persona(@Nullable String persona) {
            this.persona = persona;
            return this;
        }

        public Builder pitch(@Nullable Pitch pitch) {
            this.pitch = pitch;
            return this;
        }

        /**
         * Parameters for prompted voice generation.
         * Required in `CreateVoice` when `type` is `"prompted"`. Returned in
         * `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
         */
        public Builder prompted(@Nullable PromptedVoice prompted) {
            this.prompted = prompted;
            return this;
        }

        /**
         * Optional. ISO 3166-1 alpha-2 or UN M.49 geographic region code (e.g. "US",
         * "GB", "001").
         */
        public Builder regionCode(@Nullable String regionCode) {
            this.regionCode = regionCode;
            return this;
        }

        /**
         * Audio payload used for voice creation.
         */
        public Builder sampleAudio(@Nullable AudioData sampleAudio) {
            this.sampleAudio = sampleAudio;
            return this;
        }

        public Builder type(@Nonnull VoiceType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        /**
         * Statistics on the interaction request's token usage.
         */
        public Builder usage(@Nullable Usage usage) {
            this.usage = usage;
            return this;
        }

        public VoiceOutput build() {
            return new VoiceOutput(
                accent, context, description,
                displayName, expireTime, gender,
                id, key, languageCode,
                model, persona, pitch,
                prompted, regionCode, sampleAudio,
                type, usage);
        }

    }
}
