/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.triggers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.models.interactions.CreateAgentInteraction;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

/**
 * Trigger
 * 
 * <p>A trigger configuration that is scheduled to run an agent.
 */
public class Trigger {
    /**
     * Output only. The number of consecutive failures that have occurred
     * since the last successful execution.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("consecutive_failure_count")
    private Integer consecutiveFailureCount;

    /**
     * Output only. The time when the trigger was created.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_time")
    private OffsetDateTime createTime;

    /**
     * Optional. The display name of the trigger.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("display_name")
    private String displayName;

    /**
     * Optional. The environment ID for the trigger execution.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("environment_id")
    private String environmentId;

    /**
     * Optional. The execution timeout for the triggered interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("execution_timeout_seconds")
    private Integer executionTimeoutSeconds;

    /**
     * Required. Output only. Identifier.
     * 
     * <p>The ID of the trigger.
     */
    @JsonProperty("id")
    private String id;

    /**
     * Interaction for generating the completion using agents.
     */
    @JsonProperty("interaction")
    private CreateAgentInteraction interaction;

    /**
     * Output only. The time when the trigger was last paused.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_pause_time")
    private OffsetDateTime lastPauseTime;

    /**
     * Output only. The time when the trigger was last resumed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_resume_time")
    private OffsetDateTime lastResumeTime;

    /**
     * Output only. The time when the trigger was last run.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_run_time")
    private OffsetDateTime lastRunTime;

    /**
     * Optional. The maximum number of consecutive failures allowed before
     * the trigger is automatically paused (status becomes ERROR).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("max_consecutive_failures")
    private Integer maxConsecutiveFailures;

    /**
     * Output only. The time when the trigger is scheduled to run next.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("next_run_time")
    private OffsetDateTime nextRunTime;

    /**
     * Output only. The ID of the last interaction created by this trigger.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previous_interaction_id")
    private String previousInteractionId;

    /**
     * Required. The cron schedule on which the trigger should run.
     * Standard cron format.
     */
    @JsonProperty("schedule")
    private String schedule;

    /**
     * Output only. The current status of the trigger.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private TriggerStatus status;

    /**
     * Required. Time zone in which the schedule should be interpreted.
     */
    @JsonProperty("time_zone")
    private String timeZone;

    /**
     * Output only. The time when the trigger was last updated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_time")
    private OffsetDateTime updateTime;

    @JsonCreator
    public Trigger(
            @JsonProperty("consecutive_failure_count") @Nullable Integer consecutiveFailureCount,
            @JsonProperty("create_time") @Nullable OffsetDateTime createTime,
            @JsonProperty("display_name") @Nullable String displayName,
            @JsonProperty("environment_id") @Nullable String environmentId,
            @JsonProperty("execution_timeout_seconds") @Nullable Integer executionTimeoutSeconds,
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("interaction") @Nonnull CreateAgentInteraction interaction,
            @JsonProperty("last_pause_time") @Nullable OffsetDateTime lastPauseTime,
            @JsonProperty("last_resume_time") @Nullable OffsetDateTime lastResumeTime,
            @JsonProperty("last_run_time") @Nullable OffsetDateTime lastRunTime,
            @JsonProperty("max_consecutive_failures") @Nullable Integer maxConsecutiveFailures,
            @JsonProperty("next_run_time") @Nullable OffsetDateTime nextRunTime,
            @JsonProperty("previous_interaction_id") @Nullable String previousInteractionId,
            @JsonProperty("schedule") @Nonnull String schedule,
            @JsonProperty("status") @Nullable TriggerStatus status,
            @JsonProperty("time_zone") @Nonnull String timeZone,
            @JsonProperty("update_time") @Nullable OffsetDateTime updateTime) {
        this.consecutiveFailureCount = consecutiveFailureCount;
        this.createTime = createTime;
        this.displayName = displayName;
        this.environmentId = environmentId;
        this.executionTimeoutSeconds = executionTimeoutSeconds;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.interaction = Optional.ofNullable(interaction)
            .orElseThrow(() -> new IllegalArgumentException("interaction cannot be null"));
        this.lastPauseTime = lastPauseTime;
        this.lastResumeTime = lastResumeTime;
        this.lastRunTime = lastRunTime;
        this.maxConsecutiveFailures = maxConsecutiveFailures;
        this.nextRunTime = nextRunTime;
        this.previousInteractionId = previousInteractionId;
        this.schedule = Optional.ofNullable(schedule)
            .orElseThrow(() -> new IllegalArgumentException("schedule cannot be null"));
        this.status = status;
        this.timeZone = Optional.ofNullable(timeZone)
            .orElseThrow(() -> new IllegalArgumentException("timeZone cannot be null"));
        this.updateTime = updateTime;
    }
    
    public Trigger(
            @Nonnull String id,
            @Nonnull CreateAgentInteraction interaction,
            @Nonnull String schedule,
            @Nonnull String timeZone) {
        this(null, null, null,
            null, null, id,
            interaction, null, null,
            null, null, null,
            null, schedule, null,
            timeZone, null);
    }

    /**
     * Output only. The number of consecutive failures that have occurred
     * since the last successful execution.
     */
    public Optional<Integer> consecutiveFailureCount() {
        return Optional.ofNullable(this.consecutiveFailureCount);
    }

    /**
     * Output only. The time when the trigger was created.
     */
    public Optional<OffsetDateTime> createTime() {
        return Optional.ofNullable(this.createTime);
    }

    /**
     * Optional. The display name of the trigger.
     */
    public Optional<String> displayName() {
        return Optional.ofNullable(this.displayName);
    }

    /**
     * Optional. The environment ID for the trigger execution.
     */
    public Optional<String> environmentId() {
        return Optional.ofNullable(this.environmentId);
    }

    /**
     * Optional. The execution timeout for the triggered interaction.
     */
    public Optional<Integer> executionTimeoutSeconds() {
        return Optional.ofNullable(this.executionTimeoutSeconds);
    }

    /**
     * Required. Output only. Identifier.
     * 
     * <p>The ID of the trigger.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * Interaction for generating the completion using agents.
     */
    public Optional<CreateAgentInteraction> interaction() {
        return Optional.ofNullable(this.interaction);
    }

    /**
     * Output only. The time when the trigger was last paused.
     */
    public Optional<OffsetDateTime> lastPauseTime() {
        return Optional.ofNullable(this.lastPauseTime);
    }

    /**
     * Output only. The time when the trigger was last resumed.
     */
    public Optional<OffsetDateTime> lastResumeTime() {
        return Optional.ofNullable(this.lastResumeTime);
    }

    /**
     * Output only. The time when the trigger was last run.
     */
    public Optional<OffsetDateTime> lastRunTime() {
        return Optional.ofNullable(this.lastRunTime);
    }

    /**
     * Optional. The maximum number of consecutive failures allowed before
     * the trigger is automatically paused (status becomes ERROR).
     */
    public Optional<Integer> maxConsecutiveFailures() {
        return Optional.ofNullable(this.maxConsecutiveFailures);
    }

    /**
     * Output only. The time when the trigger is scheduled to run next.
     */
    public Optional<OffsetDateTime> nextRunTime() {
        return Optional.ofNullable(this.nextRunTime);
    }

    /**
     * Output only. The ID of the last interaction created by this trigger.
     */
    public Optional<String> previousInteractionId() {
        return Optional.ofNullable(this.previousInteractionId);
    }

    /**
     * Required. The cron schedule on which the trigger should run.
     * Standard cron format.
     */
    public Optional<String> schedule() {
        return Optional.ofNullable(this.schedule);
    }

    /**
     * Output only. The current status of the trigger.
     */
    public Optional<TriggerStatus> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Required. Time zone in which the schedule should be interpreted.
     */
    public Optional<String> timeZone() {
        return Optional.ofNullable(this.timeZone);
    }

    /**
     * Output only. The time when the trigger was last updated.
     */
    public Optional<OffsetDateTime> updateTime() {
        return Optional.ofNullable(this.updateTime);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Output only. The number of consecutive failures that have occurred
     * since the last successful execution.
     */
    public Trigger withConsecutiveFailureCount(@Nullable Integer consecutiveFailureCount) {
        this.consecutiveFailureCount = consecutiveFailureCount;
        return this;
    }


    /**
     * Output only. The time when the trigger was created.
     */
    public Trigger withCreateTime(@Nullable OffsetDateTime createTime) {
        this.createTime = createTime;
        return this;
    }


    /**
     * Optional. The display name of the trigger.
     */
    public Trigger withDisplayName(@Nullable String displayName) {
        this.displayName = displayName;
        return this;
    }


    /**
     * Optional. The environment ID for the trigger execution.
     */
    public Trigger withEnvironmentId(@Nullable String environmentId) {
        this.environmentId = environmentId;
        return this;
    }


    /**
     * Optional. The execution timeout for the triggered interaction.
     */
    public Trigger withExecutionTimeoutSeconds(@Nullable Integer executionTimeoutSeconds) {
        this.executionTimeoutSeconds = executionTimeoutSeconds;
        return this;
    }


    /**
     * Required. Output only. Identifier.
     * 
     * <p>The ID of the trigger.
     */
    public Trigger withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Interaction for generating the completion using agents.
     */
    public Trigger withInteraction(@Nonnull CreateAgentInteraction interaction) {
        this.interaction = Utils.checkNotNull(interaction, "interaction");
        return this;
    }


    /**
     * Output only. The time when the trigger was last paused.
     */
    public Trigger withLastPauseTime(@Nullable OffsetDateTime lastPauseTime) {
        this.lastPauseTime = lastPauseTime;
        return this;
    }


    /**
     * Output only. The time when the trigger was last resumed.
     */
    public Trigger withLastResumeTime(@Nullable OffsetDateTime lastResumeTime) {
        this.lastResumeTime = lastResumeTime;
        return this;
    }


    /**
     * Output only. The time when the trigger was last run.
     */
    public Trigger withLastRunTime(@Nullable OffsetDateTime lastRunTime) {
        this.lastRunTime = lastRunTime;
        return this;
    }


    /**
     * Optional. The maximum number of consecutive failures allowed before
     * the trigger is automatically paused (status becomes ERROR).
     */
    public Trigger withMaxConsecutiveFailures(@Nullable Integer maxConsecutiveFailures) {
        this.maxConsecutiveFailures = maxConsecutiveFailures;
        return this;
    }


    /**
     * Output only. The time when the trigger is scheduled to run next.
     */
    public Trigger withNextRunTime(@Nullable OffsetDateTime nextRunTime) {
        this.nextRunTime = nextRunTime;
        return this;
    }


    /**
     * Output only. The ID of the last interaction created by this trigger.
     */
    public Trigger withPreviousInteractionId(@Nullable String previousInteractionId) {
        this.previousInteractionId = previousInteractionId;
        return this;
    }


    /**
     * Required. The cron schedule on which the trigger should run.
     * Standard cron format.
     */
    public Trigger withSchedule(@Nonnull String schedule) {
        this.schedule = Utils.checkNotNull(schedule, "schedule");
        return this;
    }


    /**
     * Output only. The current status of the trigger.
     */
    public Trigger withStatus(@Nullable TriggerStatus status) {
        this.status = status;
        return this;
    }


    /**
     * Required. Time zone in which the schedule should be interpreted.
     */
    public Trigger withTimeZone(@Nonnull String timeZone) {
        this.timeZone = Utils.checkNotNull(timeZone, "timeZone");
        return this;
    }


    /**
     * Output only. The time when the trigger was last updated.
     */
    public Trigger withUpdateTime(@Nullable OffsetDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Trigger other = (Trigger) o;
        return 
            Utils.enhancedDeepEquals(this.consecutiveFailureCount, other.consecutiveFailureCount) &&
            Utils.enhancedDeepEquals(this.createTime, other.createTime) &&
            Utils.enhancedDeepEquals(this.displayName, other.displayName) &&
            Utils.enhancedDeepEquals(this.environmentId, other.environmentId) &&
            Utils.enhancedDeepEquals(this.executionTimeoutSeconds, other.executionTimeoutSeconds) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.interaction, other.interaction) &&
            Utils.enhancedDeepEquals(this.lastPauseTime, other.lastPauseTime) &&
            Utils.enhancedDeepEquals(this.lastResumeTime, other.lastResumeTime) &&
            Utils.enhancedDeepEquals(this.lastRunTime, other.lastRunTime) &&
            Utils.enhancedDeepEquals(this.maxConsecutiveFailures, other.maxConsecutiveFailures) &&
            Utils.enhancedDeepEquals(this.nextRunTime, other.nextRunTime) &&
            Utils.enhancedDeepEquals(this.previousInteractionId, other.previousInteractionId) &&
            Utils.enhancedDeepEquals(this.schedule, other.schedule) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.timeZone, other.timeZone) &&
            Utils.enhancedDeepEquals(this.updateTime, other.updateTime);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            consecutiveFailureCount, createTime, displayName,
            environmentId, executionTimeoutSeconds, id,
            interaction, lastPauseTime, lastResumeTime,
            lastRunTime, maxConsecutiveFailures, nextRunTime,
            previousInteractionId, schedule, status,
            timeZone, updateTime);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Trigger.class,
                "consecutiveFailureCount", consecutiveFailureCount,
                "createTime", createTime,
                "displayName", displayName,
                "environmentId", environmentId,
                "executionTimeoutSeconds", executionTimeoutSeconds,
                "id", id,
                "interaction", interaction,
                "lastPauseTime", lastPauseTime,
                "lastResumeTime", lastResumeTime,
                "lastRunTime", lastRunTime,
                "maxConsecutiveFailures", maxConsecutiveFailures,
                "nextRunTime", nextRunTime,
                "previousInteractionId", previousInteractionId,
                "schedule", schedule,
                "status", status,
                "timeZone", timeZone,
                "updateTime", updateTime);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Integer consecutiveFailureCount;

        private OffsetDateTime createTime;

        private String displayName;

        private String environmentId;

        private Integer executionTimeoutSeconds;

        private String id;

        private CreateAgentInteraction interaction;

        private OffsetDateTime lastPauseTime;

        private OffsetDateTime lastResumeTime;

        private OffsetDateTime lastRunTime;

        private Integer maxConsecutiveFailures;

        private OffsetDateTime nextRunTime;

        private String previousInteractionId;

        private String schedule;

        private TriggerStatus status;

        private String timeZone;

        private OffsetDateTime updateTime;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Output only. The number of consecutive failures that have occurred
         * since the last successful execution.
         */
        public Builder consecutiveFailureCount(@Nullable Integer consecutiveFailureCount) {
            this.consecutiveFailureCount = consecutiveFailureCount;
            return this;
        }

        /**
         * Output only. The time when the trigger was created.
         */
        public Builder createTime(@Nullable OffsetDateTime createTime) {
            this.createTime = createTime;
            return this;
        }

        /**
         * Optional. The display name of the trigger.
         */
        public Builder displayName(@Nullable String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Optional. The environment ID for the trigger execution.
         */
        public Builder environmentId(@Nullable String environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /**
         * Optional. The execution timeout for the triggered interaction.
         */
        public Builder executionTimeoutSeconds(@Nullable Integer executionTimeoutSeconds) {
            this.executionTimeoutSeconds = executionTimeoutSeconds;
            return this;
        }

        /**
         * Required. Output only. Identifier.
         * 
         * <p>The ID of the trigger.
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Interaction for generating the completion using agents.
         */
        public Builder interaction(@Nonnull CreateAgentInteraction interaction) {
            this.interaction = Utils.checkNotNull(interaction, "interaction");
            return this;
        }

        /**
         * Output only. The time when the trigger was last paused.
         */
        public Builder lastPauseTime(@Nullable OffsetDateTime lastPauseTime) {
            this.lastPauseTime = lastPauseTime;
            return this;
        }

        /**
         * Output only. The time when the trigger was last resumed.
         */
        public Builder lastResumeTime(@Nullable OffsetDateTime lastResumeTime) {
            this.lastResumeTime = lastResumeTime;
            return this;
        }

        /**
         * Output only. The time when the trigger was last run.
         */
        public Builder lastRunTime(@Nullable OffsetDateTime lastRunTime) {
            this.lastRunTime = lastRunTime;
            return this;
        }

        /**
         * Optional. The maximum number of consecutive failures allowed before
         * the trigger is automatically paused (status becomes ERROR).
         */
        public Builder maxConsecutiveFailures(@Nullable Integer maxConsecutiveFailures) {
            this.maxConsecutiveFailures = maxConsecutiveFailures;
            return this;
        }

        /**
         * Output only. The time when the trigger is scheduled to run next.
         */
        public Builder nextRunTime(@Nullable OffsetDateTime nextRunTime) {
            this.nextRunTime = nextRunTime;
            return this;
        }

        /**
         * Output only. The ID of the last interaction created by this trigger.
         */
        public Builder previousInteractionId(@Nullable String previousInteractionId) {
            this.previousInteractionId = previousInteractionId;
            return this;
        }

        /**
         * Required. The cron schedule on which the trigger should run.
         * Standard cron format.
         */
        public Builder schedule(@Nonnull String schedule) {
            this.schedule = Utils.checkNotNull(schedule, "schedule");
            return this;
        }

        /**
         * Output only. The current status of the trigger.
         */
        public Builder status(@Nullable TriggerStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Required. Time zone in which the schedule should be interpreted.
         */
        public Builder timeZone(@Nonnull String timeZone) {
            this.timeZone = Utils.checkNotNull(timeZone, "timeZone");
            return this;
        }

        /**
         * Output only. The time when the trigger was last updated.
         */
        public Builder updateTime(@Nullable OffsetDateTime updateTime) {
            this.updateTime = updateTime;
            return this;
        }

        public Trigger build() {
            return new Trigger(
                consecutiveFailureCount, createTime, displayName,
                environmentId, executionTimeoutSeconds, id,
                interaction, lastPauseTime, lastResumeTime,
                lastRunTime, maxConsecutiveFailures, nextRunTime,
                previousInteractionId, schedule, status,
                timeZone, updateTime);
        }

    }
}
