/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.triggers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.models.interactions.CreateAgentInteraction;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * TriggerCreateParams
 * 
 * <p>Parameters for creating a trigger.
 */
public class TriggerCreateParams {
    /**
     * Optional. The display name of the trigger.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("display_name")
    private String displayName;

    /**
     * Optional. The environment ID for the trigger execution.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("environment_id")
    private String environmentId;

    /**
     * Optional. The execution timeout for the triggered interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("execution_timeout_seconds")
    private Integer executionTimeoutSeconds;

    /**
     * Interaction for generating the completion using agents.
     */
    @JsonProperty("interaction")
    private CreateAgentInteraction interaction;

    /**
     * Optional. The maximum number of consecutive failures allowed before
     * the trigger is automatically paused (status becomes ERROR).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("max_consecutive_failures")
    private Integer maxConsecutiveFailures;

    /**
     * Required. The cron schedule on which the trigger should run.
     * Standard cron format.
     */
    @JsonProperty("schedule")
    private String schedule;

    /**
     * Required. Time zone in which the schedule should be interpreted.
     */
    @JsonProperty("time_zone")
    private String timeZone;

    @JsonCreator
    public TriggerCreateParams(
            @JsonProperty("display_name") @Nullable String displayName,
            @JsonProperty("environment_id") @Nullable String environmentId,
            @JsonProperty("execution_timeout_seconds") @Nullable Integer executionTimeoutSeconds,
            @JsonProperty("interaction") @Nonnull CreateAgentInteraction interaction,
            @JsonProperty("max_consecutive_failures") @Nullable Integer maxConsecutiveFailures,
            @JsonProperty("schedule") @Nonnull String schedule,
            @JsonProperty("time_zone") @Nonnull String timeZone) {
        this.displayName = displayName;
        this.environmentId = environmentId;
        this.executionTimeoutSeconds = executionTimeoutSeconds;
        this.interaction = Optional.ofNullable(interaction)
            .orElseThrow(() -> new IllegalArgumentException("interaction cannot be null"));
        this.maxConsecutiveFailures = maxConsecutiveFailures;
        this.schedule = Optional.ofNullable(schedule)
            .orElseThrow(() -> new IllegalArgumentException("schedule cannot be null"));
        this.timeZone = Optional.ofNullable(timeZone)
            .orElseThrow(() -> new IllegalArgumentException("timeZone cannot be null"));
    }
    
    public TriggerCreateParams(
            @Nonnull CreateAgentInteraction interaction,
            @Nonnull String schedule,
            @Nonnull String timeZone) {
        this(null, null, null,
            interaction, null, schedule,
            timeZone);
    }

    /**
     * Optional. The display name of the trigger.
     */
    public Optional<String> displayName() {
        return Optional.ofNullable(this.displayName);
    }

    /**
     * Optional. The environment ID for the trigger execution.
     */
    public Optional<String> environmentId() {
        return Optional.ofNullable(this.environmentId);
    }

    /**
     * Optional. The execution timeout for the triggered interaction.
     */
    public Optional<Integer> executionTimeoutSeconds() {
        return Optional.ofNullable(this.executionTimeoutSeconds);
    }

    /**
     * Interaction for generating the completion using agents.
     */
    public Optional<CreateAgentInteraction> interaction() {
        return Optional.ofNullable(this.interaction);
    }

    /**
     * Optional. The maximum number of consecutive failures allowed before
     * the trigger is automatically paused (status becomes ERROR).
     */
    public Optional<Integer> maxConsecutiveFailures() {
        return Optional.ofNullable(this.maxConsecutiveFailures);
    }

    /**
     * Required. The cron schedule on which the trigger should run.
     * Standard cron format.
     */
    public Optional<String> schedule() {
        return Optional.ofNullable(this.schedule);
    }

    /**
     * Required. Time zone in which the schedule should be interpreted.
     */
    public Optional<String> timeZone() {
        return Optional.ofNullable(this.timeZone);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Optional. The display name of the trigger.
     */
    public TriggerCreateParams withDisplayName(@Nullable String displayName) {
        this.displayName = displayName;
        return this;
    }


    /**
     * Optional. The environment ID for the trigger execution.
     */
    public TriggerCreateParams withEnvironmentId(@Nullable String environmentId) {
        this.environmentId = environmentId;
        return this;
    }


    /**
     * Optional. The execution timeout for the triggered interaction.
     */
    public TriggerCreateParams withExecutionTimeoutSeconds(@Nullable Integer executionTimeoutSeconds) {
        this.executionTimeoutSeconds = executionTimeoutSeconds;
        return this;
    }


    /**
     * Interaction for generating the completion using agents.
     */
    public TriggerCreateParams withInteraction(@Nonnull CreateAgentInteraction interaction) {
        this.interaction = Utils.checkNotNull(interaction, "interaction");
        return this;
    }


    /**
     * Optional. The maximum number of consecutive failures allowed before
     * the trigger is automatically paused (status becomes ERROR).
     */
    public TriggerCreateParams withMaxConsecutiveFailures(@Nullable Integer maxConsecutiveFailures) {
        this.maxConsecutiveFailures = maxConsecutiveFailures;
        return this;
    }


    /**
     * Required. The cron schedule on which the trigger should run.
     * Standard cron format.
     */
    public TriggerCreateParams withSchedule(@Nonnull String schedule) {
        this.schedule = Utils.checkNotNull(schedule, "schedule");
        return this;
    }


    /**
     * Required. Time zone in which the schedule should be interpreted.
     */
    public TriggerCreateParams withTimeZone(@Nonnull String timeZone) {
        this.timeZone = Utils.checkNotNull(timeZone, "timeZone");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TriggerCreateParams other = (TriggerCreateParams) o;
        return 
            Utils.enhancedDeepEquals(this.displayName, other.displayName) &&
            Utils.enhancedDeepEquals(this.environmentId, other.environmentId) &&
            Utils.enhancedDeepEquals(this.executionTimeoutSeconds, other.executionTimeoutSeconds) &&
            Utils.enhancedDeepEquals(this.interaction, other.interaction) &&
            Utils.enhancedDeepEquals(this.maxConsecutiveFailures, other.maxConsecutiveFailures) &&
            Utils.enhancedDeepEquals(this.schedule, other.schedule) &&
            Utils.enhancedDeepEquals(this.timeZone, other.timeZone);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            displayName, environmentId, executionTimeoutSeconds,
            interaction, maxConsecutiveFailures, schedule,
            timeZone);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TriggerCreateParams.class,
                "displayName", displayName,
                "environmentId", environmentId,
                "executionTimeoutSeconds", executionTimeoutSeconds,
                "interaction", interaction,
                "maxConsecutiveFailures", maxConsecutiveFailures,
                "schedule", schedule,
                "timeZone", timeZone);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String displayName;

        private String environmentId;

        private Integer executionTimeoutSeconds;

        private CreateAgentInteraction interaction;

        private Integer maxConsecutiveFailures;

        private String schedule;

        private String timeZone;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Optional. The display name of the trigger.
         */
        public Builder displayName(@Nullable String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Optional. The environment ID for the trigger execution.
         */
        public Builder environmentId(@Nullable String environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /**
         * Optional. The execution timeout for the triggered interaction.
         */
        public Builder executionTimeoutSeconds(@Nullable Integer executionTimeoutSeconds) {
            this.executionTimeoutSeconds = executionTimeoutSeconds;
            return this;
        }

        /**
         * Interaction for generating the completion using agents.
         */
        public Builder interaction(@Nonnull CreateAgentInteraction interaction) {
            this.interaction = Utils.checkNotNull(interaction, "interaction");
            return this;
        }

        /**
         * Optional. The maximum number of consecutive failures allowed before
         * the trigger is automatically paused (status becomes ERROR).
         */
        public Builder maxConsecutiveFailures(@Nullable Integer maxConsecutiveFailures) {
            this.maxConsecutiveFailures = maxConsecutiveFailures;
            return this;
        }

        /**
         * Required. The cron schedule on which the trigger should run.
         * Standard cron format.
         */
        public Builder schedule(@Nonnull String schedule) {
            this.schedule = Utils.checkNotNull(schedule, "schedule");
            return this;
        }

        /**
         * Required. Time zone in which the schedule should be interpreted.
         */
        public Builder timeZone(@Nonnull String timeZone) {
            this.timeZone = Utils.checkNotNull(timeZone, "timeZone");
            return this;
        }

        public TriggerCreateParams build() {
            return new TriggerCreateParams(
                displayName, environmentId, executionTimeoutSeconds,
                interaction, maxConsecutiveFailures, schedule,
                timeZone);
        }

    }
}
