/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.google.genai.gaos.utils.SpeakeasyMetadata;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetEnvironmentFilesRequest {
    /**
     * API version for request routing.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=api_version")
    private String apiVersion;

    /**
     * The ID of the environment whose snapshot to read.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=environment")
    private String environment;

    /**
     * Path of the file or directory inside the environment workspace, relative to its root (e.g. src).
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,allowReserved=true,name=path")
    private String path;

    /**
     * Optional. Maximum number of entries to return per page (for directory listing).
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")
    private Integer pageSize;

    /**
     * Optional. Pagination token for directory listing.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_token")
    private String pageToken;

    /**
     * Optional. If true and the path is a directory, recursively lists all files.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=recursive")
    private Boolean recursive;

    @JsonCreator
    public GetEnvironmentFilesRequest(
            @Nullable String apiVersion,
            @Nonnull String environment,
            @Nonnull String path,
            @Nullable Integer pageSize,
            @Nullable String pageToken,
            @Nullable Boolean recursive) {
        this.apiVersion = apiVersion;
        this.environment = Optional.ofNullable(environment)
            .orElseThrow(() -> new IllegalArgumentException("environment cannot be null"));
        this.path = Optional.ofNullable(path)
            .orElseThrow(() -> new IllegalArgumentException("path cannot be null"));
        this.pageSize = pageSize;
        this.pageToken = pageToken;
        this.recursive = recursive;
    }
    
    public GetEnvironmentFilesRequest(
            @Nonnull String environment,
            @Nonnull String path) {
        this(null, environment, path,
            null, null, null);
    }

    /**
     * API version for request routing.
     */
    public Optional<String> apiVersion() {
        return Optional.ofNullable(this.apiVersion);
    }

    /**
     * The ID of the environment whose snapshot to read.
     */
    public Optional<String> environment() {
        return Optional.ofNullable(this.environment);
    }

    /**
     * Path of the file or directory inside the environment workspace, relative to its root (e.g. src).
     */
    public Optional<String> path() {
        return Optional.ofNullable(this.path);
    }

    /**
     * Optional. Maximum number of entries to return per page (for directory listing).
     */
    public Optional<Integer> pageSize() {
        return Optional.ofNullable(this.pageSize);
    }

    /**
     * Optional. Pagination token for directory listing.
     */
    public Optional<String> pageToken() {
        return Optional.ofNullable(this.pageToken);
    }

    /**
     * Optional. If true and the path is a directory, recursively lists all files.
     */
    public Optional<Boolean> recursive() {
        return Optional.ofNullable(this.recursive);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * API version for request routing.
     */
    public GetEnvironmentFilesRequest withApiVersion(@Nullable String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }


    /**
     * The ID of the environment whose snapshot to read.
     */
    public GetEnvironmentFilesRequest withEnvironment(@Nonnull String environment) {
        this.environment = Utils.checkNotNull(environment, "environment");
        return this;
    }


    /**
     * Path of the file or directory inside the environment workspace, relative to its root (e.g. src).
     */
    public GetEnvironmentFilesRequest withPath(@Nonnull String path) {
        this.path = Utils.checkNotNull(path, "path");
        return this;
    }


    /**
     * Optional. Maximum number of entries to return per page (for directory listing).
     */
    public GetEnvironmentFilesRequest withPageSize(@Nullable Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }


    /**
     * Optional. Pagination token for directory listing.
     */
    public GetEnvironmentFilesRequest withPageToken(@Nullable String pageToken) {
        this.pageToken = pageToken;
        return this;
    }


    /**
     * Optional. If true and the path is a directory, recursively lists all files.
     */
    public GetEnvironmentFilesRequest withRecursive(@Nullable Boolean recursive) {
        this.recursive = recursive;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetEnvironmentFilesRequest other = (GetEnvironmentFilesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.apiVersion, other.apiVersion) &&
            Utils.enhancedDeepEquals(this.environment, other.environment) &&
            Utils.enhancedDeepEquals(this.path, other.path) &&
            Utils.enhancedDeepEquals(this.pageSize, other.pageSize) &&
            Utils.enhancedDeepEquals(this.pageToken, other.pageToken) &&
            Utils.enhancedDeepEquals(this.recursive, other.recursive);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            apiVersion, environment, path,
            pageSize, pageToken, recursive);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetEnvironmentFilesRequest.class,
                "apiVersion", apiVersion,
                "environment", environment,
                "path", path,
                "pageSize", pageSize,
                "pageToken", pageToken,
                "recursive", recursive);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String apiVersion;

        private String environment;

        private String path;

        private Integer pageSize;

        private String pageToken;

        private Boolean recursive;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * API version for request routing.
         */
        public Builder apiVersion(@Nullable String apiVersion) {
            this.apiVersion = apiVersion;
            return this;
        }

        /**
         * The ID of the environment whose snapshot to read.
         */
        public Builder environment(@Nonnull String environment) {
            this.environment = Utils.checkNotNull(environment, "environment");
            return this;
        }

        /**
         * Path of the file or directory inside the environment workspace, relative to its root (e.g. src).
         */
        public Builder path(@Nonnull String path) {
            this.path = Utils.checkNotNull(path, "path");
            return this;
        }

        /**
         * Optional. Maximum number of entries to return per page (for directory listing).
         */
        public Builder pageSize(@Nullable Integer pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /**
         * Optional. Pagination token for directory listing.
         */
        public Builder pageToken(@Nullable String pageToken) {
            this.pageToken = pageToken;
            return this;
        }

        /**
         * Optional. If true and the path is a directory, recursively lists all files.
         */
        public Builder recursive(@Nullable Boolean recursive) {
            this.recursive = recursive;
            return this;
        }

        public GetEnvironmentFilesRequest build() {
            return new GetEnvironmentFilesRequest(
                apiVersion, environment, path,
                pageSize, pageToken, recursive);
        }

    }
}
