/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Deprecated;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * CreateModelInteraction
 * 
 * <p>Interaction for generating the completion using models.
 */
public class CreateModelInteraction {
    /**
     * Input only. Whether to run the model interaction in the background.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("background")
    private Boolean background;

    /**
     * The name of the cached content used as context to serve the prediction. Note: only used in explicit
     * caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed
     * cost savings.
     * 
     * <p>Format: cachedContents/{cachedContent}
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cached_content")
    @Deprecated
    private String cachedContent;

    /**
     * Opaque token to resume a long decode. Output: set when status is
     * INCOMPLETE and decoding can be resumed. Input: pass the latest token
     * back unchanged in CreateInteraction to continue decoding.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("continuation_token")
    private String continuationToken;

    /**
     * The environment configuration for the interaction. Can be an object
     * specifying remote environment sources or a string referencing an existing
     * environment ID.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("environment")
    private CreateModelInteractionEnvironment environment;

    /**
     * Configuration parameters for model interactions.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("generation_config")
    private GenerationConfig generationConfig;

    /**
     * The input for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("input")
    private InteractionsInput input;

    /**
     * The labels with user-defined metadata for the request.
     * 
     * <p>Label keys and values can be no longer than 63 characters
     * (Unicode codepoints) and can only contain lowercase letters, numeric
     * characters, underscores, and dashes. International characters are allowed.
     * Label values are optional. Label keys must start with a letter.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("labels")
    private Map<String, String> labels;

    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    @JsonProperty("model")
    private Model model;

    /**
     * The ID of the previous interaction, if any.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previous_interaction_id")
    private String previousInteractionId;

    /**
     * Enforces that the generated response is a JSON object that complies with
     * the JSON schema specified in this field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_format")
    private CreateModelInteractionResponseFormat responseFormat;

    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_mime_type")
    @Deprecated
    private String responseMimeType;

    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_modalities")
    @Deprecated
    private List<ResponseModality> responseModalities;

    /**
     * Safety settings for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("safety_settings")
    private List<SafetySetting> safetySettings;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_tier")
    private ServiceTier serviceTier;

    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("store")
    private Boolean store;

    /**
     * Input only. Whether the interaction will be streamed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stream")
    private Boolean stream;

    /**
     * System instruction for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("system_instruction")
    private String systemInstruction;

    /**
     * A list of tool declarations the model may call during interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tools")
    private List<Tool> tools;

    /**
     * Message for configuring webhook events for a request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("webhook_config")
    private WebhookConfig webhookConfig;

    @JsonCreator
    public CreateModelInteraction(
            @JsonProperty("background") @Nullable Boolean background,
            @JsonProperty("cached_content") @Nullable String cachedContent,
            @JsonProperty("continuation_token") @Nullable String continuationToken,
            @JsonProperty("environment") @Nullable CreateModelInteractionEnvironment environment,
            @JsonProperty("generation_config") @Nullable GenerationConfig generationConfig,
            @JsonProperty("input") @Nullable InteractionsInput input,
            @JsonProperty("labels") @Nullable Map<String, String> labels,
            @JsonProperty("model") @Nonnull Model model,
            @JsonProperty("previous_interaction_id") @Nullable String previousInteractionId,
            @JsonProperty("response_format") @Nullable CreateModelInteractionResponseFormat responseFormat,
            @JsonProperty("response_mime_type") @Nullable String responseMimeType,
            @JsonProperty("response_modalities") @Nullable List<ResponseModality> responseModalities,
            @JsonProperty("safety_settings") @Nullable List<SafetySetting> safetySettings,
            @JsonProperty("service_tier") @Nullable ServiceTier serviceTier,
            @JsonProperty("store") @Nullable Boolean store,
            @JsonProperty("stream") @Nullable Boolean stream,
            @JsonProperty("system_instruction") @Nullable String systemInstruction,
            @JsonProperty("tools") @Nullable List<Tool> tools,
            @JsonProperty("webhook_config") @Nullable WebhookConfig webhookConfig) {
        this.background = background;
        this.cachedContent = cachedContent;
        this.continuationToken = continuationToken;
        this.environment = environment;
        this.generationConfig = generationConfig;
        this.input = input;
        this.labels = labels;
        this.model = Optional.ofNullable(model)
            .orElseThrow(() -> new IllegalArgumentException("model cannot be null"));
        this.previousInteractionId = previousInteractionId;
        this.responseFormat = responseFormat;
        this.responseMimeType = responseMimeType;
        this.responseModalities = responseModalities;
        this.safetySettings = safetySettings;
        this.serviceTier = serviceTier;
        this.store = store;
        this.stream = stream;
        this.systemInstruction = systemInstruction;
        this.tools = tools;
        this.webhookConfig = webhookConfig;
    }
    
    public CreateModelInteraction(
            @Nonnull Model model) {
        this(null, null, null,
            null, null, null,
            null, model, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null);
    }

    /**
     * Input only. Whether to run the model interaction in the background.
     */
    public Optional<Boolean> background() {
        return Optional.ofNullable(this.background);
    }

    /**
     * The name of the cached content used as context to serve the prediction. Note: only used in explicit
     * caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed
     * cost savings.
     * 
     * <p>Format: cachedContents/{cachedContent}
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<String> cachedContent() {
        return Optional.ofNullable(this.cachedContent);
    }

    /**
     * Opaque token to resume a long decode. Output: set when status is
     * INCOMPLETE and decoding can be resumed. Input: pass the latest token
     * back unchanged in CreateInteraction to continue decoding.
     */
    public Optional<String> continuationToken() {
        return Optional.ofNullable(this.continuationToken);
    }

    /**
     * The environment configuration for the interaction. Can be an object
     * specifying remote environment sources or a string referencing an existing
     * environment ID.
     */
    public Optional<CreateModelInteractionEnvironment> environment() {
        return Optional.ofNullable(this.environment);
    }

    /**
     * Configuration parameters for model interactions.
     */
    public Optional<GenerationConfig> generationConfig() {
        return Optional.ofNullable(this.generationConfig);
    }

    /**
     * The input for the interaction.
     */
    public Optional<InteractionsInput> input() {
        return Optional.ofNullable(this.input);
    }

    /**
     * The labels with user-defined metadata for the request.
     * 
     * <p>Label keys and values can be no longer than 63 characters
     * (Unicode codepoints) and can only contain lowercase letters, numeric
     * characters, underscores, and dashes. International characters are allowed.
     * Label values are optional. Label keys must start with a letter.
     */
    public Optional<Map<String, String>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    public Optional<Model> model() {
        return Optional.ofNullable(this.model);
    }

    /**
     * The ID of the previous interaction, if any.
     */
    public Optional<String> previousInteractionId() {
        return Optional.ofNullable(this.previousInteractionId);
    }

    /**
     * Enforces that the generated response is a JSON object that complies with
     * the JSON schema specified in this field.
     */
    public Optional<CreateModelInteractionResponseFormat> responseFormat() {
        return Optional.ofNullable(this.responseFormat);
    }

    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<String> responseMimeType() {
        return Optional.ofNullable(this.responseMimeType);
    }

    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<List<ResponseModality>> responseModalities() {
        return Optional.ofNullable(this.responseModalities);
    }

    /**
     * Safety settings for the interaction.
     */
    public Optional<List<SafetySetting>> safetySettings() {
        return Optional.ofNullable(this.safetySettings);
    }

    public Optional<ServiceTier> serviceTier() {
        return Optional.ofNullable(this.serviceTier);
    }

    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    public Optional<Boolean> store() {
        return Optional.ofNullable(this.store);
    }

    /**
     * Input only. Whether the interaction will be streamed.
     */
    public Optional<Boolean> stream() {
        return Optional.ofNullable(this.stream);
    }

    /**
     * System instruction for the interaction.
     */
    public Optional<String> systemInstruction() {
        return Optional.ofNullable(this.systemInstruction);
    }

    /**
     * A list of tool declarations the model may call during interaction.
     */
    public Optional<List<Tool>> tools() {
        return Optional.ofNullable(this.tools);
    }

    /**
     * Message for configuring webhook events for a request.
     */
    public Optional<WebhookConfig> webhookConfig() {
        return Optional.ofNullable(this.webhookConfig);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Input only. Whether to run the model interaction in the background.
     */
    public CreateModelInteraction withBackground(@Nullable Boolean background) {
        this.background = background;
        return this;
    }


    /**
     * The name of the cached content used as context to serve the prediction. Note: only used in explicit
     * caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed
     * cost savings.
     * 
     * <p>Format: cachedContents/{cachedContent}
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateModelInteraction withCachedContent(@Nullable String cachedContent) {
        this.cachedContent = cachedContent;
        return this;
    }


    /**
     * Opaque token to resume a long decode. Output: set when status is
     * INCOMPLETE and decoding can be resumed. Input: pass the latest token
     * back unchanged in CreateInteraction to continue decoding.
     */
    public CreateModelInteraction withContinuationToken(@Nullable String continuationToken) {
        this.continuationToken = continuationToken;
        return this;
    }


    /**
     * The environment configuration for the interaction. Can be an object
     * specifying remote environment sources or a string referencing an existing
     * environment ID.
     */
    public CreateModelInteraction withEnvironment(@Nullable CreateModelInteractionEnvironment environment) {
        this.environment = environment;
        return this;
    }


    /**
     * Configuration parameters for model interactions.
     */
    public CreateModelInteraction withGenerationConfig(@Nullable GenerationConfig generationConfig) {
        this.generationConfig = generationConfig;
        return this;
    }


    /**
     * The input for the interaction.
     */
    public CreateModelInteraction withInput(@Nullable InteractionsInput input) {
        this.input = input;
        return this;
    }


    /**
     * The labels with user-defined metadata for the request.
     * 
     * <p>Label keys and values can be no longer than 63 characters
     * (Unicode codepoints) and can only contain lowercase letters, numeric
     * characters, underscores, and dashes. International characters are allowed.
     * Label values are optional. Label keys must start with a letter.
     */
    public CreateModelInteraction withLabels(@Nullable Map<String, String> labels) {
        this.labels = labels;
        return this;
    }


    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    public CreateModelInteraction withModel(@Nonnull Model model) {
        this.model = Utils.checkNotNull(model, "model");
        return this;
    }


    /**
     * The ID of the previous interaction, if any.
     */
    public CreateModelInteraction withPreviousInteractionId(@Nullable String previousInteractionId) {
        this.previousInteractionId = previousInteractionId;
        return this;
    }


    /**
     * Enforces that the generated response is a JSON object that complies with
     * the JSON schema specified in this field.
     */
    public CreateModelInteraction withResponseFormat(@Nullable CreateModelInteractionResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }


    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateModelInteraction withResponseMimeType(@Nullable String responseMimeType) {
        this.responseMimeType = responseMimeType;
        return this;
    }


    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateModelInteraction withResponseModalities(@Nullable List<ResponseModality> responseModalities) {
        this.responseModalities = responseModalities;
        return this;
    }


    /**
     * Safety settings for the interaction.
     */
    public CreateModelInteraction withSafetySettings(@Nullable List<SafetySetting> safetySettings) {
        this.safetySettings = safetySettings;
        return this;
    }


    public CreateModelInteraction withServiceTier(@Nullable ServiceTier serviceTier) {
        this.serviceTier = serviceTier;
        return this;
    }


    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    public CreateModelInteraction withStore(@Nullable Boolean store) {
        this.store = store;
        return this;
    }


    /**
     * Input only. Whether the interaction will be streamed.
     */
    public CreateModelInteraction withStream(@Nullable Boolean stream) {
        this.stream = stream;
        return this;
    }


    /**
     * System instruction for the interaction.
     */
    public CreateModelInteraction withSystemInstruction(@Nullable String systemInstruction) {
        this.systemInstruction = systemInstruction;
        return this;
    }


    /**
     * A list of tool declarations the model may call during interaction.
     */
    public CreateModelInteraction withTools(@Nullable List<Tool> tools) {
        this.tools = tools;
        return this;
    }


    /**
     * Message for configuring webhook events for a request.
     */
    public CreateModelInteraction withWebhookConfig(@Nullable WebhookConfig webhookConfig) {
        this.webhookConfig = webhookConfig;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateModelInteraction other = (CreateModelInteraction) o;
        return 
            Utils.enhancedDeepEquals(this.background, other.background) &&
            Utils.enhancedDeepEquals(this.cachedContent, other.cachedContent) &&
            Utils.enhancedDeepEquals(this.continuationToken, other.continuationToken) &&
            Utils.enhancedDeepEquals(this.environment, other.environment) &&
            Utils.enhancedDeepEquals(this.generationConfig, other.generationConfig) &&
            Utils.enhancedDeepEquals(this.input, other.input) &&
            Utils.enhancedDeepEquals(this.labels, other.labels) &&
            Utils.enhancedDeepEquals(this.model, other.model) &&
            Utils.enhancedDeepEquals(this.previousInteractionId, other.previousInteractionId) &&
            Utils.enhancedDeepEquals(this.responseFormat, other.responseFormat) &&
            Utils.enhancedDeepEquals(this.responseMimeType, other.responseMimeType) &&
            Utils.enhancedDeepEquals(this.responseModalities, other.responseModalities) &&
            Utils.enhancedDeepEquals(this.safetySettings, other.safetySettings) &&
            Utils.enhancedDeepEquals(this.serviceTier, other.serviceTier) &&
            Utils.enhancedDeepEquals(this.store, other.store) &&
            Utils.enhancedDeepEquals(this.stream, other.stream) &&
            Utils.enhancedDeepEquals(this.systemInstruction, other.systemInstruction) &&
            Utils.enhancedDeepEquals(this.tools, other.tools) &&
            Utils.enhancedDeepEquals(this.webhookConfig, other.webhookConfig);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            background, cachedContent, continuationToken,
            environment, generationConfig, input,
            labels, model, previousInteractionId,
            responseFormat, responseMimeType, responseModalities,
            safetySettings, serviceTier, store,
            stream, systemInstruction, tools,
            webhookConfig);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateModelInteraction.class,
                "background", background,
                "cachedContent", cachedContent,
                "continuationToken", continuationToken,
                "environment", environment,
                "generationConfig", generationConfig,
                "input", input,
                "labels", labels,
                "model", model,
                "previousInteractionId", previousInteractionId,
                "responseFormat", responseFormat,
                "responseMimeType", responseMimeType,
                "responseModalities", responseModalities,
                "safetySettings", safetySettings,
                "serviceTier", serviceTier,
                "store", store,
                "stream", stream,
                "systemInstruction", systemInstruction,
                "tools", tools,
                "webhookConfig", webhookConfig);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Boolean background;

        @Deprecated
        private String cachedContent;

        private String continuationToken;

        private CreateModelInteractionEnvironment environment;

        private GenerationConfig generationConfig;

        private InteractionsInput input;

        private Map<String, String> labels;

        private Model model;

        private String previousInteractionId;

        private CreateModelInteractionResponseFormat responseFormat;

        @Deprecated
        private String responseMimeType;

        @Deprecated
        private List<ResponseModality> responseModalities;

        private List<SafetySetting> safetySettings;

        private ServiceTier serviceTier;

        private Boolean store;

        private Boolean stream;

        private String systemInstruction;

        private List<Tool> tools;

        private WebhookConfig webhookConfig;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Input only. Whether to run the model interaction in the background.
         */
        public Builder background(@Nullable Boolean background) {
            this.background = background;
            return this;
        }

        /**
         * The name of the cached content used as context to serve the prediction. Note: only used in explicit
         * caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed
         * cost savings.
         * 
         * <p>Format: cachedContents/{cachedContent}
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder cachedContent(@Nullable String cachedContent) {
            this.cachedContent = cachedContent;
            return this;
        }

        /**
         * Opaque token to resume a long decode. Output: set when status is
         * INCOMPLETE and decoding can be resumed. Input: pass the latest token
         * back unchanged in CreateInteraction to continue decoding.
         */
        public Builder continuationToken(@Nullable String continuationToken) {
            this.continuationToken = continuationToken;
            return this;
        }

        /**
         * The environment configuration for the interaction. Can be an object
         * specifying remote environment sources or a string referencing an existing
         * environment ID.
         */
        public Builder environment(@Nullable CreateModelInteractionEnvironment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * Configuration parameters for model interactions.
         */
        public Builder generationConfig(@Nullable GenerationConfig generationConfig) {
            this.generationConfig = generationConfig;
            return this;
        }

        /**
         * The input for the interaction.
         */
        public Builder input(@Nullable InteractionsInput input) {
            this.input = input;
            return this;
        }

        /**
         * The labels with user-defined metadata for the request.
         * 
         * <p>Label keys and values can be no longer than 63 characters
         * (Unicode codepoints) and can only contain lowercase letters, numeric
         * characters, underscores, and dashes. International characters are allowed.
         * Label values are optional. Label keys must start with a letter.
         */
        public Builder labels(@Nullable Map<String, String> labels) {
            this.labels = labels;
            return this;
        }

        /**
         * The model that will complete your prompt.\n\nSee
         * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
         */
        public Builder model(@Nonnull Model model) {
            this.model = Utils.checkNotNull(model, "model");
            return this;
        }

        /**
         * The ID of the previous interaction, if any.
         */
        public Builder previousInteractionId(@Nullable String previousInteractionId) {
            this.previousInteractionId = previousInteractionId;
            return this;
        }

        /**
         * Enforces that the generated response is a JSON object that complies with
         * the JSON schema specified in this field.
         */
        public Builder responseFormat(@Nullable CreateModelInteractionResponseFormat responseFormat) {
            this.responseFormat = responseFormat;
            return this;
        }

        /**
         * The mime type of the response. This is required if response_format is set.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder responseMimeType(@Nullable String responseMimeType) {
            this.responseMimeType = responseMimeType;
            return this;
        }

        /**
         * The requested modalities of the response (TEXT, IMAGE, AUDIO).
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder responseModalities(@Nullable List<ResponseModality> responseModalities) {
            this.responseModalities = responseModalities;
            return this;
        }

        /**
         * Safety settings for the interaction.
         */
        public Builder safetySettings(@Nullable List<SafetySetting> safetySettings) {
            this.safetySettings = safetySettings;
            return this;
        }

        public Builder serviceTier(@Nullable ServiceTier serviceTier) {
            this.serviceTier = serviceTier;
            return this;
        }

        /**
         * Input only. Whether to store the response and request for later retrieval.
         */
        public Builder store(@Nullable Boolean store) {
            this.store = store;
            return this;
        }

        public Builder model(@Nonnull String model) {
            this.model = Model.of(Utils.checkNotNull(model, "model"));
            return this;
        }

        /**
         * Input only. Whether the interaction will be streamed.
         */
        public Builder stream(@Nullable Boolean stream) {
            this.stream = stream;
            return this;
        }

        /**
         * System instruction for the interaction.
         */
        public Builder systemInstruction(@Nullable String systemInstruction) {
            this.systemInstruction = systemInstruction;
            return this;
        }

        /**
         * A list of tool declarations the model may call during interaction.
         */
        public Builder tools(@Nullable List<Tool> tools) {
            this.tools = tools;
            return this;
        }

        /**
         * Message for configuring webhook events for a request.
         */
        public Builder webhookConfig(@Nullable WebhookConfig webhookConfig) {
            this.webhookConfig = webhookConfig;
            return this;
        }

        public CreateModelInteraction build() {
            return new CreateModelInteraction(
                background, cachedContent, continuationToken,
                environment, generationConfig, input,
                labels, model, previousInteractionId,
                responseFormat, responseMimeType, responseModalities,
                safetySettings, serviceTier, store,
                stream, systemInstruction, tools,
                webhookConfig);
        }

    }
}
