/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Deprecated;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * GenerationConfig
 * 
 * <p>Configuration parameters for model interactions.
 */
public class GenerationConfig {
    /**
     * The configuration for image interaction.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("image_config")
    @Deprecated
    private ImageConfig imageConfig;

    /**
     * The maximum number of tokens to include in the response.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("max_output_tokens")
    private Integer maxOutputTokens;

    /**
     * Seed used in decoding for reproducibility.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("seed")
    private Integer seed;

    /**
     * Optional. Speech and multi-speaker configuration.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("speech_config")
    private SpeechConfigUnion speechConfig;

    /**
     * A list of character sequences that will stop output interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stop_sequences")
    private List<String> stopSequences;

    /**
     * Controls the randomness of the output.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("temperature")
    @Deprecated
    private Float temperature;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("thinking_level")
    private ThinkingLevel thinkingLevel;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("thinking_summaries")
    private ThinkingSummaries thinkingSummaries;

    /**
     * The tool choice configuration.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tool_choice")
    private ToolChoice toolChoice;

    /**
     * The maximum cumulative probability of tokens to consider when sampling.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("top_p")
    @Deprecated
    private Float topP;

    /**
     * Configuration for speech recognition (transcription).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transcription_config")
    private TranscriptionConfig transcriptionConfig;

    /**
     * Configuration options for video generation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("video_config")
    private VideoConfig videoConfig;

    @JsonCreator
    public GenerationConfig(
            @JsonProperty("image_config") @Nullable ImageConfig imageConfig,
            @JsonProperty("max_output_tokens") @Nullable Integer maxOutputTokens,
            @JsonProperty("seed") @Nullable Integer seed,
            @JsonProperty("speech_config") @Nullable SpeechConfigUnion speechConfig,
            @JsonProperty("stop_sequences") @Nullable List<String> stopSequences,
            @JsonProperty("temperature") @Nullable Float temperature,
            @JsonProperty("thinking_level") @Nullable ThinkingLevel thinkingLevel,
            @JsonProperty("thinking_summaries") @Nullable ThinkingSummaries thinkingSummaries,
            @JsonProperty("tool_choice") @Nullable ToolChoice toolChoice,
            @JsonProperty("top_p") @Nullable Float topP,
            @JsonProperty("transcription_config") @Nullable TranscriptionConfig transcriptionConfig,
            @JsonProperty("video_config") @Nullable VideoConfig videoConfig) {
        this.imageConfig = imageConfig;
        this.maxOutputTokens = maxOutputTokens;
        this.seed = seed;
        this.speechConfig = speechConfig;
        this.stopSequences = stopSequences;
        this.temperature = temperature;
        this.thinkingLevel = thinkingLevel;
        this.thinkingSummaries = thinkingSummaries;
        this.toolChoice = toolChoice;
        this.topP = topP;
        this.transcriptionConfig = transcriptionConfig;
        this.videoConfig = videoConfig;
    }
    
    public GenerationConfig() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null);
    }

    /**
     * The configuration for image interaction.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<ImageConfig> imageConfig() {
        return Optional.ofNullable(this.imageConfig);
    }

    /**
     * The maximum number of tokens to include in the response.
     */
    public Optional<Integer> maxOutputTokens() {
        return Optional.ofNullable(this.maxOutputTokens);
    }

    /**
     * Seed used in decoding for reproducibility.
     */
    public Optional<Integer> seed() {
        return Optional.ofNullable(this.seed);
    }

    /**
     * Optional. Speech and multi-speaker configuration.
     */
    public Optional<SpeechConfigUnion> speechConfig() {
        return Optional.ofNullable(this.speechConfig);
    }

    /**
     * A list of character sequences that will stop output interaction.
     */
    public Optional<List<String>> stopSequences() {
        return Optional.ofNullable(this.stopSequences);
    }

    /**
     * Controls the randomness of the output.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<Float> temperature() {
        return Optional.ofNullable(this.temperature);
    }

    public Optional<ThinkingLevel> thinkingLevel() {
        return Optional.ofNullable(this.thinkingLevel);
    }

    public Optional<ThinkingSummaries> thinkingSummaries() {
        return Optional.ofNullable(this.thinkingSummaries);
    }

    /**
     * The tool choice configuration.
     */
    public Optional<ToolChoice> toolChoice() {
        return Optional.ofNullable(this.toolChoice);
    }

    /**
     * The maximum cumulative probability of tokens to consider when sampling.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<Float> topP() {
        return Optional.ofNullable(this.topP);
    }

    /**
     * Configuration for speech recognition (transcription).
     */
    public Optional<TranscriptionConfig> transcriptionConfig() {
        return Optional.ofNullable(this.transcriptionConfig);
    }

    /**
     * Configuration options for video generation.
     */
    public Optional<VideoConfig> videoConfig() {
        return Optional.ofNullable(this.videoConfig);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The configuration for image interaction.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public GenerationConfig withImageConfig(@Nullable ImageConfig imageConfig) {
        this.imageConfig = imageConfig;
        return this;
    }


    /**
     * The maximum number of tokens to include in the response.
     */
    public GenerationConfig withMaxOutputTokens(@Nullable Integer maxOutputTokens) {
        this.maxOutputTokens = maxOutputTokens;
        return this;
    }


    /**
     * Seed used in decoding for reproducibility.
     */
    public GenerationConfig withSeed(@Nullable Integer seed) {
        this.seed = seed;
        return this;
    }


    /**
     * Optional. Speech and multi-speaker configuration.
     */
    public GenerationConfig withSpeechConfig(@Nullable SpeechConfigUnion speechConfig) {
        this.speechConfig = speechConfig;
        return this;
    }


    /**
     * A list of character sequences that will stop output interaction.
     */
    public GenerationConfig withStopSequences(@Nullable List<String> stopSequences) {
        this.stopSequences = stopSequences;
        return this;
    }


    /**
     * Controls the randomness of the output.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public GenerationConfig withTemperature(@Nullable Float temperature) {
        this.temperature = temperature;
        return this;
    }


    public GenerationConfig withThinkingLevel(@Nullable ThinkingLevel thinkingLevel) {
        this.thinkingLevel = thinkingLevel;
        return this;
    }


    public GenerationConfig withThinkingSummaries(@Nullable ThinkingSummaries thinkingSummaries) {
        this.thinkingSummaries = thinkingSummaries;
        return this;
    }


    /**
     * The tool choice configuration.
     */
    public GenerationConfig withToolChoice(@Nullable ToolChoice toolChoice) {
        this.toolChoice = toolChoice;
        return this;
    }


    /**
     * The maximum cumulative probability of tokens to consider when sampling.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public GenerationConfig withTopP(@Nullable Float topP) {
        this.topP = topP;
        return this;
    }


    /**
     * Configuration for speech recognition (transcription).
     */
    public GenerationConfig withTranscriptionConfig(@Nullable TranscriptionConfig transcriptionConfig) {
        this.transcriptionConfig = transcriptionConfig;
        return this;
    }


    /**
     * Configuration options for video generation.
     */
    public GenerationConfig withVideoConfig(@Nullable VideoConfig videoConfig) {
        this.videoConfig = videoConfig;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GenerationConfig other = (GenerationConfig) o;
        return 
            Utils.enhancedDeepEquals(this.imageConfig, other.imageConfig) &&
            Utils.enhancedDeepEquals(this.maxOutputTokens, other.maxOutputTokens) &&
            Utils.enhancedDeepEquals(this.seed, other.seed) &&
            Utils.enhancedDeepEquals(this.speechConfig, other.speechConfig) &&
            Utils.enhancedDeepEquals(this.stopSequences, other.stopSequences) &&
            Utils.enhancedDeepEquals(this.temperature, other.temperature) &&
            Utils.enhancedDeepEquals(this.thinkingLevel, other.thinkingLevel) &&
            Utils.enhancedDeepEquals(this.thinkingSummaries, other.thinkingSummaries) &&
            Utils.enhancedDeepEquals(this.toolChoice, other.toolChoice) &&
            Utils.enhancedDeepEquals(this.topP, other.topP) &&
            Utils.enhancedDeepEquals(this.transcriptionConfig, other.transcriptionConfig) &&
            Utils.enhancedDeepEquals(this.videoConfig, other.videoConfig);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            imageConfig, maxOutputTokens, seed,
            speechConfig, stopSequences, temperature,
            thinkingLevel, thinkingSummaries, toolChoice,
            topP, transcriptionConfig, videoConfig);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GenerationConfig.class,
                "imageConfig", imageConfig,
                "maxOutputTokens", maxOutputTokens,
                "seed", seed,
                "speechConfig", speechConfig,
                "stopSequences", stopSequences,
                "temperature", temperature,
                "thinkingLevel", thinkingLevel,
                "thinkingSummaries", thinkingSummaries,
                "toolChoice", toolChoice,
                "topP", topP,
                "transcriptionConfig", transcriptionConfig,
                "videoConfig", videoConfig);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        @Deprecated
        private ImageConfig imageConfig;

        private Integer maxOutputTokens;

        private Integer seed;

        private SpeechConfigUnion speechConfig;

        private List<String> stopSequences;

        @Deprecated
        private Float temperature;

        private ThinkingLevel thinkingLevel;

        private ThinkingSummaries thinkingSummaries;

        private ToolChoice toolChoice;

        @Deprecated
        private Float topP;

        private TranscriptionConfig transcriptionConfig;

        private VideoConfig videoConfig;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The configuration for image interaction.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder imageConfig(@Nullable ImageConfig imageConfig) {
            this.imageConfig = imageConfig;
            return this;
        }

        /**
         * The maximum number of tokens to include in the response.
         */
        public Builder maxOutputTokens(@Nullable Integer maxOutputTokens) {
            this.maxOutputTokens = maxOutputTokens;
            return this;
        }

        /**
         * Seed used in decoding for reproducibility.
         */
        public Builder seed(@Nullable Integer seed) {
            this.seed = seed;
            return this;
        }

        /**
         * Optional. Speech and multi-speaker configuration.
         */
        public Builder speechConfig(@Nullable SpeechConfigUnion speechConfig) {
            this.speechConfig = speechConfig;
            return this;
        }

        /**
         * A list of character sequences that will stop output interaction.
         */
        public Builder stopSequences(@Nullable List<String> stopSequences) {
            this.stopSequences = stopSequences;
            return this;
        }

        /**
         * Controls the randomness of the output.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder temperature(@Nullable Float temperature) {
            this.temperature = temperature;
            return this;
        }

        public Builder thinkingLevel(@Nullable ThinkingLevel thinkingLevel) {
            this.thinkingLevel = thinkingLevel;
            return this;
        }

        public Builder thinkingSummaries(@Nullable ThinkingSummaries thinkingSummaries) {
            this.thinkingSummaries = thinkingSummaries;
            return this;
        }

        /**
         * The tool choice configuration.
         */
        public Builder toolChoice(@Nullable ToolChoice toolChoice) {
            this.toolChoice = toolChoice;
            return this;
        }

        /**
         * The maximum cumulative probability of tokens to consider when sampling.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder topP(@Nullable Float topP) {
            this.topP = topP;
            return this;
        }

        /**
         * Configuration for speech recognition (transcription).
         */
        public Builder transcriptionConfig(@Nullable TranscriptionConfig transcriptionConfig) {
            this.transcriptionConfig = transcriptionConfig;
            return this;
        }

        /**
         * Configuration options for video generation.
         */
        public Builder videoConfig(@Nullable VideoConfig videoConfig) {
            this.videoConfig = videoConfig;
            return this;
        }

        public GenerationConfig build() {
            return new GenerationConfig(
                imageConfig, maxOutputTokens, seed,
                speechConfig, stopSequences, temperature,
                thinkingLevel, thinkingSummaries, toolChoice,
                topP, transcriptionConfig, videoConfig);
        }

    }
}
