/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * InteractionSseEventInteraction
 * 
 * <p>Partial interaction resource emitted by interaction lifecycle SSE events.
 * Streaming lifecycle payloads may omit fields that are only available on
 * full non-streaming Interaction responses.
 */
public class InteractionSseEventInteraction {
    /**
     * The agent to interact with.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("agent")
    private String agent;

    /**
     * Output only. Opaque token to resume a long decode when status is incomplete.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("continuation_token")
    private String continuationToken;

    /**
     * Output only. The time at which the response was created in ISO 8601 format.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created")
    private String created;

    /**
     * Required. Output only. A unique identifier for the interaction completion.
     */
    @JsonProperty("id")
    private String id;

    /**
     * The model that will complete your prompt.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("model")
    private String model;

    /**
     * Output only. The resource type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("object")
    private String object;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_tier")
    private ServiceTier serviceTier;

    /**
     * Required. Output only. The status of the interaction.
     */
    @JsonProperty("status")
    private InteractionSseEventInteractionStatus status;

    /**
     * Output only. The steps that make up the interaction, if included in this event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("steps")
    private List<Step> steps;

    /**
     * Output only. The time at which the response was last updated in ISO 8601 format.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updated")
    private String updated;

    /**
     * Statistics on the interaction request's token usage.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("usage")
    private Usage usage;

    @JsonCreator
    public InteractionSseEventInteraction(
            @JsonProperty("agent") @Nullable String agent,
            @JsonProperty("continuation_token") @Nullable String continuationToken,
            @JsonProperty("created") @Nullable String created,
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("model") @Nullable String model,
            @JsonProperty("object") @Nullable String object,
            @JsonProperty("service_tier") @Nullable ServiceTier serviceTier,
            @JsonProperty("status") @Nonnull InteractionSseEventInteractionStatus status,
            @JsonProperty("steps") @Nullable List<Step> steps,
            @JsonProperty("updated") @Nullable String updated,
            @JsonProperty("usage") @Nullable Usage usage) {
        this.agent = agent;
        this.continuationToken = continuationToken;
        this.created = created;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.model = model;
        this.object = object;
        this.serviceTier = serviceTier;
        this.status = Optional.ofNullable(status)
            .orElseThrow(() -> new IllegalArgumentException("status cannot be null"));
        this.steps = steps;
        this.updated = updated;
        this.usage = usage;
    }
    
    public InteractionSseEventInteraction(
            @Nonnull String id,
            @Nonnull InteractionSseEventInteractionStatus status) {
        this(null, null, null,
            id, null, null,
            null, status, null,
            null, null);
    }

    /**
     * The agent to interact with.
     */
    public Optional<String> agent() {
        return Optional.ofNullable(this.agent);
    }

    /**
     * Output only. Opaque token to resume a long decode when status is incomplete.
     */
    public Optional<String> continuationToken() {
        return Optional.ofNullable(this.continuationToken);
    }

    /**
     * Output only. The time at which the response was created in ISO 8601 format.
     */
    public Optional<String> created() {
        return Optional.ofNullable(this.created);
    }

    /**
     * Required. Output only. A unique identifier for the interaction completion.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The model that will complete your prompt.
     */
    public Optional<String> model() {
        return Optional.ofNullable(this.model);
    }

    /**
     * Output only. The resource type.
     */
    public Optional<String> object() {
        return Optional.ofNullable(this.object);
    }

    public Optional<ServiceTier> serviceTier() {
        return Optional.ofNullable(this.serviceTier);
    }

    /**
     * Required. Output only. The status of the interaction.
     */
    public Optional<InteractionSseEventInteractionStatus> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Output only. The steps that make up the interaction, if included in this event.
     */
    public Optional<List<Step>> steps() {
        return Optional.ofNullable(this.steps);
    }

    /**
     * Output only. The time at which the response was last updated in ISO 8601 format.
     */
    public Optional<String> updated() {
        return Optional.ofNullable(this.updated);
    }

    /**
     * Statistics on the interaction request's token usage.
     */
    public Optional<Usage> usage() {
        return Optional.ofNullable(this.usage);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The agent to interact with.
     */
    public InteractionSseEventInteraction withAgent(@Nullable String agent) {
        this.agent = agent;
        return this;
    }


    /**
     * Output only. Opaque token to resume a long decode when status is incomplete.
     */
    public InteractionSseEventInteraction withContinuationToken(@Nullable String continuationToken) {
        this.continuationToken = continuationToken;
        return this;
    }


    /**
     * Output only. The time at which the response was created in ISO 8601 format.
     */
    public InteractionSseEventInteraction withCreated(@Nullable String created) {
        this.created = created;
        return this;
    }


    /**
     * Required. Output only. A unique identifier for the interaction completion.
     */
    public InteractionSseEventInteraction withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * The model that will complete your prompt.
     */
    public InteractionSseEventInteraction withModel(@Nullable String model) {
        this.model = model;
        return this;
    }


    /**
     * Output only. The resource type.
     */
    public InteractionSseEventInteraction withObject(@Nullable String object) {
        this.object = object;
        return this;
    }


    public InteractionSseEventInteraction withServiceTier(@Nullable ServiceTier serviceTier) {
        this.serviceTier = serviceTier;
        return this;
    }


    /**
     * Required. Output only. The status of the interaction.
     */
    public InteractionSseEventInteraction withStatus(@Nonnull InteractionSseEventInteractionStatus status) {
        this.status = Utils.checkNotNull(status, "status");
        return this;
    }


    /**
     * Output only. The steps that make up the interaction, if included in this event.
     */
    public InteractionSseEventInteraction withSteps(@Nullable List<Step> steps) {
        this.steps = steps;
        return this;
    }


    /**
     * Output only. The time at which the response was last updated in ISO 8601 format.
     */
    public InteractionSseEventInteraction withUpdated(@Nullable String updated) {
        this.updated = updated;
        return this;
    }


    /**
     * Statistics on the interaction request's token usage.
     */
    public InteractionSseEventInteraction withUsage(@Nullable Usage usage) {
        this.usage = usage;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InteractionSseEventInteraction other = (InteractionSseEventInteraction) o;
        return 
            Utils.enhancedDeepEquals(this.agent, other.agent) &&
            Utils.enhancedDeepEquals(this.continuationToken, other.continuationToken) &&
            Utils.enhancedDeepEquals(this.created, other.created) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.model, other.model) &&
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.serviceTier, other.serviceTier) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.steps, other.steps) &&
            Utils.enhancedDeepEquals(this.updated, other.updated) &&
            Utils.enhancedDeepEquals(this.usage, other.usage);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            agent, continuationToken, created,
            id, model, object,
            serviceTier, status, steps,
            updated, usage);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InteractionSseEventInteraction.class,
                "agent", agent,
                "continuationToken", continuationToken,
                "created", created,
                "id", id,
                "model", model,
                "object", object,
                "serviceTier", serviceTier,
                "status", status,
                "steps", steps,
                "updated", updated,
                "usage", usage);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String agent;

        private String continuationToken;

        private String created;

        private String id;

        private String model;

        private String object;

        private ServiceTier serviceTier;

        private InteractionSseEventInteractionStatus status;

        private List<Step> steps;

        private String updated;

        private Usage usage;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The agent to interact with.
         */
        public Builder agent(@Nullable String agent) {
            this.agent = agent;
            return this;
        }

        /**
         * Output only. Opaque token to resume a long decode when status is incomplete.
         */
        public Builder continuationToken(@Nullable String continuationToken) {
            this.continuationToken = continuationToken;
            return this;
        }

        /**
         * Output only. The time at which the response was created in ISO 8601 format.
         */
        public Builder created(@Nullable String created) {
            this.created = created;
            return this;
        }

        /**
         * Required. Output only. A unique identifier for the interaction completion.
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * The model that will complete your prompt.
         */
        public Builder model(@Nullable String model) {
            this.model = model;
            return this;
        }

        /**
         * Output only. The resource type.
         */
        public Builder object(@Nullable String object) {
            this.object = object;
            return this;
        }

        public Builder serviceTier(@Nullable ServiceTier serviceTier) {
            this.serviceTier = serviceTier;
            return this;
        }

        /**
         * Required. Output only. The status of the interaction.
         */
        public Builder status(@Nonnull InteractionSseEventInteractionStatus status) {
            this.status = Utils.checkNotNull(status, "status");
            return this;
        }

        /**
         * Output only. The steps that make up the interaction, if included in this event.
         */
        public Builder steps(@Nullable List<Step> steps) {
            this.steps = steps;
            return this;
        }

        /**
         * Output only. The time at which the response was last updated in ISO 8601 format.
         */
        public Builder updated(@Nullable String updated) {
            this.updated = updated;
            return this;
        }

        /**
         * Statistics on the interaction request's token usage.
         */
        public Builder usage(@Nullable Usage usage) {
            this.usage = usage;
            return this;
        }

        public InteractionSseEventInteraction build() {
            return new InteractionSseEventInteraction(
                agent, continuationToken, created,
                id, model, object,
                serviceTier, status, steps,
                updated, usage);
        }

    }
}
