/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Deprecated;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Interaction
 * 
 * <p>The Interaction resource.
 */
public class Interaction {
    /**
     * The agent to interact with.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("agent")
    private AgentOption agent;

    /**
     * Configuration parameters for the agent interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("agent_config")
    private InteractionAgentConfig agentConfig;

    /**
     * The name of the cached content used as context to serve the prediction. Note: only used in explicit
     * caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed
     * cost savings.
     * 
     * <p>Format: cachedContents/{cachedContent}
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cached_content")
    @Deprecated
    private String cachedContent;

    /**
     * Opaque token to resume a long decode. Output: set when status is
     * INCOMPLETE and decoding can be resumed. Input: pass the latest token
     * back unchanged in CreateInteraction to continue decoding.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("continuation_token")
    private String continuationToken;

    /**
     * Required. Output only. The time at which the response was created in ISO 8601 format
     * (YYYY-MM-DDThh:mm:ssZ).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created")
    private String created;

    /**
     * The environment configuration for the interaction. Can be an object
     * specifying remote environment sources or a string referencing an existing
     * environment ID.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("environment")
    private InteractionEnvironment environment;

    /**
     * Output only. The environment ID for the interaction. Only populated if environment
     * config is set in the request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("environment_id")
    private String environmentId;

    /**
     * Output only. Diagnostic faults / platform errors recorded on the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errors")
    private List<Error> errors;

    /**
     * Configuration parameters for model interactions.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("generation_config")
    private GenerationConfig generationConfig;

    /**
     * Required. Output only. A unique identifier for the interaction completion.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    /**
     * The input for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("input")
    private InteractionsInput input;

    /**
     * The labels with user-defined metadata for the request.
     * 
     * <p>Label keys and values can be no longer than 63 characters
     * (Unicode codepoints) and can only contain lowercase letters, numeric
     * characters, underscores, and dashes. International characters are allowed.
     * Label values are optional. Label keys must start with a letter.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("labels")
    private Map<String, String> labels;

    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("model")
    private Model model;

    /**
     * An audio content block.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("output_audio")
    private AudioContent outputAudio;

    /**
     * An image content block.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("output_image")
    private ImageContent outputImage;

    /**
     * Concatenated text from the last model output in response to the current request.
     * 
     * <p>Note: this is added by the SDK.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("output_text")
    private String outputText;

    /**
     * A video content block.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("output_video")
    private VideoContent outputVideo;

    /**
     * The ID of the previous interaction, if any.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previous_interaction_id")
    private String previousInteractionId;

    /**
     * Enforces that the generated response is a JSON object that complies with
     * the JSON schema specified in this field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_format")
    private InteractionResponseFormat responseFormat;

    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_mime_type")
    @Deprecated
    private String responseMimeType;

    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_modalities")
    @Deprecated
    private List<ResponseModality> responseModalities;

    /**
     * Safety settings for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("safety_settings")
    private List<SafetySetting> safetySettings;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_tier")
    private ServiceTier serviceTier;

    /**
     * Required. Output only. The status of the interaction.
     */
    @JsonProperty("status")
    private InteractionStatus status;

    /**
     * Required. Output only. The steps that make up the interaction, when included in the response.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("steps")
    private List<Step> steps;

    /**
     * System instruction for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("system_instruction")
    private String systemInstruction;

    /**
     * A list of tool declarations the model may call during interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tools")
    private List<Tool> tools;

    /**
     * Required. Output only. The time at which the response was last updated in ISO 8601 format
     * (YYYY-MM-DDThh:mm:ssZ).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updated")
    private String updated;

    /**
     * Statistics on the interaction request's token usage.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("usage")
    private Usage usage;

    /**
     * Message for configuring webhook events for a request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("webhook_config")
    private WebhookConfig webhookConfig;

    @JsonCreator
    public Interaction(
            @JsonProperty("agent") @Nullable AgentOption agent,
            @JsonProperty("agent_config") @Nullable InteractionAgentConfig agentConfig,
            @JsonProperty("cached_content") @Nullable String cachedContent,
            @JsonProperty("continuation_token") @Nullable String continuationToken,
            @JsonProperty("created") @Nullable String created,
            @JsonProperty("environment") @Nullable InteractionEnvironment environment,
            @JsonProperty("environment_id") @Nullable String environmentId,
            @JsonProperty("errors") @Nullable List<Error> errors,
            @JsonProperty("generation_config") @Nullable GenerationConfig generationConfig,
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("input") @Nullable InteractionsInput input,
            @JsonProperty("labels") @Nullable Map<String, String> labels,
            @JsonProperty("model") @Nullable Model model,
            @JsonProperty("output_audio") @Nullable AudioContent outputAudio,
            @JsonProperty("output_image") @Nullable ImageContent outputImage,
            @JsonProperty("output_text") @Nullable String outputText,
            @JsonProperty("output_video") @Nullable VideoContent outputVideo,
            @JsonProperty("previous_interaction_id") @Nullable String previousInteractionId,
            @JsonProperty("response_format") @Nullable InteractionResponseFormat responseFormat,
            @JsonProperty("response_mime_type") @Nullable String responseMimeType,
            @JsonProperty("response_modalities") @Nullable List<ResponseModality> responseModalities,
            @JsonProperty("safety_settings") @Nullable List<SafetySetting> safetySettings,
            @JsonProperty("service_tier") @Nullable ServiceTier serviceTier,
            @JsonProperty("status") @Nonnull InteractionStatus status,
            @JsonProperty("steps") @Nullable List<Step> steps,
            @JsonProperty("system_instruction") @Nullable String systemInstruction,
            @JsonProperty("tools") @Nullable List<Tool> tools,
            @JsonProperty("updated") @Nullable String updated,
            @JsonProperty("usage") @Nullable Usage usage,
            @JsonProperty("webhook_config") @Nullable WebhookConfig webhookConfig) {
        this.agent = agent;
        this.agentConfig = agentConfig;
        this.cachedContent = cachedContent;
        this.continuationToken = continuationToken;
        this.created = created;
        this.environment = environment;
        this.environmentId = environmentId;
        this.errors = errors;
        this.generationConfig = generationConfig;
        this.id = Optional.ofNullable(id)
            .orElse(Builder._SINGLETON_VALUE_Id.value());
        this.input = input;
        this.labels = labels;
        this.model = model;
        this.outputAudio = outputAudio;
        this.outputImage = outputImage;
        this.outputText = outputText;
        this.outputVideo = outputVideo;
        this.previousInteractionId = previousInteractionId;
        this.responseFormat = responseFormat;
        this.responseMimeType = responseMimeType;
        this.responseModalities = responseModalities;
        this.safetySettings = safetySettings;
        this.serviceTier = serviceTier;
        this.status = Optional.ofNullable(status)
            .orElseThrow(() -> new IllegalArgumentException("status cannot be null"));
        this.steps = steps;
        this.systemInstruction = systemInstruction;
        this.tools = tools;
        this.updated = updated;
        this.usage = usage;
        this.webhookConfig = webhookConfig;
    }
    
    public Interaction(
            @Nonnull InteractionStatus status) {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, status,
            null, null, null,
            null, null, null);
    }

    /**
     * The agent to interact with.
     */
    public Optional<AgentOption> agent() {
        return Optional.ofNullable(this.agent);
    }

    /**
     * Configuration parameters for the agent interaction.
     */
    public Optional<InteractionAgentConfig> agentConfig() {
        return Optional.ofNullable(this.agentConfig);
    }

    /**
     * The name of the cached content used as context to serve the prediction. Note: only used in explicit
     * caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed
     * cost savings.
     * 
     * <p>Format: cachedContents/{cachedContent}
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<String> cachedContent() {
        return Optional.ofNullable(this.cachedContent);
    }

    /**
     * Opaque token to resume a long decode. Output: set when status is
     * INCOMPLETE and decoding can be resumed. Input: pass the latest token
     * back unchanged in CreateInteraction to continue decoding.
     */
    public Optional<String> continuationToken() {
        return Optional.ofNullable(this.continuationToken);
    }

    /**
     * Required. Output only. The time at which the response was created in ISO 8601 format
     * (YYYY-MM-DDThh:mm:ssZ).
     */
    public Optional<String> created() {
        return Optional.ofNullable(this.created);
    }

    /**
     * The environment configuration for the interaction. Can be an object
     * specifying remote environment sources or a string referencing an existing
     * environment ID.
     */
    public Optional<InteractionEnvironment> environment() {
        return Optional.ofNullable(this.environment);
    }

    /**
     * Output only. The environment ID for the interaction. Only populated if environment
     * config is set in the request.
     */
    public Optional<String> environmentId() {
        return Optional.ofNullable(this.environmentId);
    }

    /**
     * Output only. Diagnostic faults / platform errors recorded on the interaction.
     */
    public Optional<List<Error>> errors() {
        return Optional.ofNullable(this.errors);
    }

    /**
     * Configuration parameters for model interactions.
     */
    public Optional<GenerationConfig> generationConfig() {
        return Optional.ofNullable(this.generationConfig);
    }

    /**
     * Required. Output only. A unique identifier for the interaction completion.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The input for the interaction.
     */
    public Optional<InteractionsInput> input() {
        return Optional.ofNullable(this.input);
    }

    /**
     * The labels with user-defined metadata for the request.
     * 
     * <p>Label keys and values can be no longer than 63 characters
     * (Unicode codepoints) and can only contain lowercase letters, numeric
     * characters, underscores, and dashes. International characters are allowed.
     * Label values are optional. Label keys must start with a letter.
     */
    public Optional<Map<String, String>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    public Optional<Model> model() {
        return Optional.ofNullable(this.model);
    }

    /**
     * An audio content block.
     */
    public Optional<AudioContent> outputAudio() {
        return Optional.ofNullable(this.outputAudio);
    }

    /**
     * An image content block.
     */
    public Optional<ImageContent> outputImage() {
        return Optional.ofNullable(this.outputImage);
    }

    /**
     * Concatenated text from the last model output in response to the current request.
     * 
     * <p>Note: this is added by the SDK.
     */
    public Optional<String> outputText() {
        return Optional.ofNullable(this.outputText);
    }

    /**
     * A video content block.
     */
    public Optional<VideoContent> outputVideo() {
        return Optional.ofNullable(this.outputVideo);
    }

    /**
     * The ID of the previous interaction, if any.
     */
    public Optional<String> previousInteractionId() {
        return Optional.ofNullable(this.previousInteractionId);
    }

    /**
     * Enforces that the generated response is a JSON object that complies with
     * the JSON schema specified in this field.
     */
    public Optional<InteractionResponseFormat> responseFormat() {
        return Optional.ofNullable(this.responseFormat);
    }

    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<String> responseMimeType() {
        return Optional.ofNullable(this.responseMimeType);
    }

    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<List<ResponseModality>> responseModalities() {
        return Optional.ofNullable(this.responseModalities);
    }

    /**
     * Safety settings for the interaction.
     */
    public Optional<List<SafetySetting>> safetySettings() {
        return Optional.ofNullable(this.safetySettings);
    }

    public Optional<ServiceTier> serviceTier() {
        return Optional.ofNullable(this.serviceTier);
    }

    /**
     * Required. Output only. The status of the interaction.
     */
    public Optional<InteractionStatus> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Required. Output only. The steps that make up the interaction, when included in the response.
     */
    public Optional<List<Step>> steps() {
        return Optional.ofNullable(this.steps);
    }

    /**
     * System instruction for the interaction.
     */
    public Optional<String> systemInstruction() {
        return Optional.ofNullable(this.systemInstruction);
    }

    /**
     * A list of tool declarations the model may call during interaction.
     */
    public Optional<List<Tool>> tools() {
        return Optional.ofNullable(this.tools);
    }

    /**
     * Required. Output only. The time at which the response was last updated in ISO 8601 format
     * (YYYY-MM-DDThh:mm:ssZ).
     */
    public Optional<String> updated() {
        return Optional.ofNullable(this.updated);
    }

    /**
     * Statistics on the interaction request's token usage.
     */
    public Optional<Usage> usage() {
        return Optional.ofNullable(this.usage);
    }

    /**
     * Message for configuring webhook events for a request.
     */
    public Optional<WebhookConfig> webhookConfig() {
        return Optional.ofNullable(this.webhookConfig);
    }

    @JsonProperty("outputs")
    public void setOutputs(List<Content> outputs) {
        if (outputs != null && !outputs.isEmpty()) {
            ModelOutputStep modelOutputStep = ModelOutputStep.builder()
                .content(outputs)
                .build();
            Step step = modelOutputStep;
            this.steps = java.util.Collections.singletonList(step);
        }
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The agent to interact with.
     */
    public Interaction withAgent(@Nullable AgentOption agent) {
        this.agent = agent;
        return this;
    }


    /**
     * Configuration parameters for the agent interaction.
     */
    public Interaction withAgentConfig(@Nullable InteractionAgentConfig agentConfig) {
        this.agentConfig = agentConfig;
        return this;
    }


    /**
     * The name of the cached content used as context to serve the prediction. Note: only used in explicit
     * caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed
     * cost savings.
     * 
     * <p>Format: cachedContents/{cachedContent}
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Interaction withCachedContent(@Nullable String cachedContent) {
        this.cachedContent = cachedContent;
        return this;
    }


    /**
     * Opaque token to resume a long decode. Output: set when status is
     * INCOMPLETE and decoding can be resumed. Input: pass the latest token
     * back unchanged in CreateInteraction to continue decoding.
     */
    public Interaction withContinuationToken(@Nullable String continuationToken) {
        this.continuationToken = continuationToken;
        return this;
    }


    /**
     * Required. Output only. The time at which the response was created in ISO 8601 format
     * (YYYY-MM-DDThh:mm:ssZ).
     */
    public Interaction withCreated(@Nullable String created) {
        this.created = created;
        return this;
    }


    /**
     * The environment configuration for the interaction. Can be an object
     * specifying remote environment sources or a string referencing an existing
     * environment ID.
     */
    public Interaction withEnvironment(@Nullable InteractionEnvironment environment) {
        this.environment = environment;
        return this;
    }


    /**
     * Output only. The environment ID for the interaction. Only populated if environment
     * config is set in the request.
     */
    public Interaction withEnvironmentId(@Nullable String environmentId) {
        this.environmentId = environmentId;
        return this;
    }


    /**
     * Output only. Diagnostic faults / platform errors recorded on the interaction.
     */
    public Interaction withErrors(@Nullable List<Error> errors) {
        this.errors = errors;
        return this;
    }


    /**
     * Configuration parameters for model interactions.
     */
    public Interaction withGenerationConfig(@Nullable GenerationConfig generationConfig) {
        this.generationConfig = generationConfig;
        return this;
    }


    /**
     * Required. Output only. A unique identifier for the interaction completion.
     */
    public Interaction withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    /**
     * The input for the interaction.
     */
    public Interaction withInput(@Nullable InteractionsInput input) {
        this.input = input;
        return this;
    }


    /**
     * The labels with user-defined metadata for the request.
     * 
     * <p>Label keys and values can be no longer than 63 characters
     * (Unicode codepoints) and can only contain lowercase letters, numeric
     * characters, underscores, and dashes. International characters are allowed.
     * Label values are optional. Label keys must start with a letter.
     */
    public Interaction withLabels(@Nullable Map<String, String> labels) {
        this.labels = labels;
        return this;
    }


    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    public Interaction withModel(@Nullable Model model) {
        this.model = model;
        return this;
    }


    /**
     * An audio content block.
     */
    public Interaction withOutputAudio(@Nullable AudioContent outputAudio) {
        this.outputAudio = outputAudio;
        return this;
    }


    /**
     * An image content block.
     */
    public Interaction withOutputImage(@Nullable ImageContent outputImage) {
        this.outputImage = outputImage;
        return this;
    }


    /**
     * Concatenated text from the last model output in response to the current request.
     * 
     * <p>Note: this is added by the SDK.
     */
    public Interaction withOutputText(@Nullable String outputText) {
        this.outputText = outputText;
        return this;
    }


    /**
     * A video content block.
     */
    public Interaction withOutputVideo(@Nullable VideoContent outputVideo) {
        this.outputVideo = outputVideo;
        return this;
    }


    /**
     * The ID of the previous interaction, if any.
     */
    public Interaction withPreviousInteractionId(@Nullable String previousInteractionId) {
        this.previousInteractionId = previousInteractionId;
        return this;
    }


    /**
     * Enforces that the generated response is a JSON object that complies with
     * the JSON schema specified in this field.
     */
    public Interaction withResponseFormat(@Nullable InteractionResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }


    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Interaction withResponseMimeType(@Nullable String responseMimeType) {
        this.responseMimeType = responseMimeType;
        return this;
    }


    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Interaction withResponseModalities(@Nullable List<ResponseModality> responseModalities) {
        this.responseModalities = responseModalities;
        return this;
    }


    /**
     * Safety settings for the interaction.
     */
    public Interaction withSafetySettings(@Nullable List<SafetySetting> safetySettings) {
        this.safetySettings = safetySettings;
        return this;
    }


    public Interaction withServiceTier(@Nullable ServiceTier serviceTier) {
        this.serviceTier = serviceTier;
        return this;
    }


    /**
     * Required. Output only. The status of the interaction.
     */
    public Interaction withStatus(@Nonnull InteractionStatus status) {
        this.status = Utils.checkNotNull(status, "status");
        return this;
    }


    /**
     * Required. Output only. The steps that make up the interaction, when included in the response.
     */
    public Interaction withSteps(@Nullable List<Step> steps) {
        this.steps = steps;
        return this;
    }


    /**
     * System instruction for the interaction.
     */
    public Interaction withSystemInstruction(@Nullable String systemInstruction) {
        this.systemInstruction = systemInstruction;
        return this;
    }


    /**
     * A list of tool declarations the model may call during interaction.
     */
    public Interaction withTools(@Nullable List<Tool> tools) {
        this.tools = tools;
        return this;
    }


    /**
     * Required. Output only. The time at which the response was last updated in ISO 8601 format
     * (YYYY-MM-DDThh:mm:ssZ).
     */
    public Interaction withUpdated(@Nullable String updated) {
        this.updated = updated;
        return this;
    }


    /**
     * Statistics on the interaction request's token usage.
     */
    public Interaction withUsage(@Nullable Usage usage) {
        this.usage = usage;
        return this;
    }


    /**
     * Message for configuring webhook events for a request.
     */
    public Interaction withWebhookConfig(@Nullable WebhookConfig webhookConfig) {
        this.webhookConfig = webhookConfig;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Interaction other = (Interaction) o;
        return 
            Utils.enhancedDeepEquals(this.agent, other.agent) &&
            Utils.enhancedDeepEquals(this.agentConfig, other.agentConfig) &&
            Utils.enhancedDeepEquals(this.cachedContent, other.cachedContent) &&
            Utils.enhancedDeepEquals(this.continuationToken, other.continuationToken) &&
            Utils.enhancedDeepEquals(this.created, other.created) &&
            Utils.enhancedDeepEquals(this.environment, other.environment) &&
            Utils.enhancedDeepEquals(this.environmentId, other.environmentId) &&
            Utils.enhancedDeepEquals(this.errors, other.errors) &&
            Utils.enhancedDeepEquals(this.generationConfig, other.generationConfig) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.input, other.input) &&
            Utils.enhancedDeepEquals(this.labels, other.labels) &&
            Utils.enhancedDeepEquals(this.model, other.model) &&
            Utils.enhancedDeepEquals(this.outputAudio, other.outputAudio) &&
            Utils.enhancedDeepEquals(this.outputImage, other.outputImage) &&
            Utils.enhancedDeepEquals(this.outputText, other.outputText) &&
            Utils.enhancedDeepEquals(this.outputVideo, other.outputVideo) &&
            Utils.enhancedDeepEquals(this.previousInteractionId, other.previousInteractionId) &&
            Utils.enhancedDeepEquals(this.responseFormat, other.responseFormat) &&
            Utils.enhancedDeepEquals(this.responseMimeType, other.responseMimeType) &&
            Utils.enhancedDeepEquals(this.responseModalities, other.responseModalities) &&
            Utils.enhancedDeepEquals(this.safetySettings, other.safetySettings) &&
            Utils.enhancedDeepEquals(this.serviceTier, other.serviceTier) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.steps, other.steps) &&
            Utils.enhancedDeepEquals(this.systemInstruction, other.systemInstruction) &&
            Utils.enhancedDeepEquals(this.tools, other.tools) &&
            Utils.enhancedDeepEquals(this.updated, other.updated) &&
            Utils.enhancedDeepEquals(this.usage, other.usage) &&
            Utils.enhancedDeepEquals(this.webhookConfig, other.webhookConfig);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            agent, agentConfig, cachedContent,
            continuationToken, created, environment,
            environmentId, errors, generationConfig,
            id, input, labels,
            model, outputAudio, outputImage,
            outputText, outputVideo, previousInteractionId,
            responseFormat, responseMimeType, responseModalities,
            safetySettings, serviceTier, status,
            steps, systemInstruction, tools,
            updated, usage, webhookConfig);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Interaction.class,
                "agent", agent,
                "agentConfig", agentConfig,
                "cachedContent", cachedContent,
                "continuationToken", continuationToken,
                "created", created,
                "environment", environment,
                "environmentId", environmentId,
                "errors", errors,
                "generationConfig", generationConfig,
                "id", id,
                "input", input,
                "labels", labels,
                "model", model,
                "outputAudio", outputAudio,
                "outputImage", outputImage,
                "outputText", outputText,
                "outputVideo", outputVideo,
                "previousInteractionId", previousInteractionId,
                "responseFormat", responseFormat,
                "responseMimeType", responseMimeType,
                "responseModalities", responseModalities,
                "safetySettings", safetySettings,
                "serviceTier", serviceTier,
                "status", status,
                "steps", steps,
                "systemInstruction", systemInstruction,
                "tools", tools,
                "updated", updated,
                "usage", usage,
                "webhookConfig", webhookConfig);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AgentOption agent;

        private InteractionAgentConfig agentConfig;

        @Deprecated
        private String cachedContent;

        private String continuationToken;

        private String created;

        private InteractionEnvironment environment;

        private String environmentId;

        private List<Error> errors;

        private GenerationConfig generationConfig;

        private String id;

        private InteractionsInput input;

        private Map<String, String> labels;

        private Model model;

        private AudioContent outputAudio;

        private ImageContent outputImage;

        private String outputText;

        private VideoContent outputVideo;

        private String previousInteractionId;

        private InteractionResponseFormat responseFormat;

        @Deprecated
        private String responseMimeType;

        @Deprecated
        private List<ResponseModality> responseModalities;

        private List<SafetySetting> safetySettings;

        private ServiceTier serviceTier;

        private InteractionStatus status;

        private List<Step> steps;

        private String systemInstruction;

        private List<Tool> tools;

        private String updated;

        private Usage usage;

        private WebhookConfig webhookConfig;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The agent to interact with.
         */
        public Builder agent(@Nullable AgentOption agent) {
            this.agent = agent;
            return this;
        }

        /**
         * Configuration parameters for the agent interaction.
         */
        public Builder agentConfig(@Nullable InteractionAgentConfig agentConfig) {
            this.agentConfig = agentConfig;
            return this;
        }

        /**
         * The name of the cached content used as context to serve the prediction. Note: only used in explicit
         * caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed
         * cost savings.
         * 
         * <p>Format: cachedContents/{cachedContent}
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder cachedContent(@Nullable String cachedContent) {
            this.cachedContent = cachedContent;
            return this;
        }

        /**
         * Opaque token to resume a long decode. Output: set when status is
         * INCOMPLETE and decoding can be resumed. Input: pass the latest token
         * back unchanged in CreateInteraction to continue decoding.
         */
        public Builder continuationToken(@Nullable String continuationToken) {
            this.continuationToken = continuationToken;
            return this;
        }

        /**
         * Required. Output only. The time at which the response was created in ISO 8601 format
         * (YYYY-MM-DDThh:mm:ssZ).
         */
        public Builder created(@Nullable String created) {
            this.created = created;
            return this;
        }

        /**
         * The environment configuration for the interaction. Can be an object
         * specifying remote environment sources or a string referencing an existing
         * environment ID.
         */
        public Builder environment(@Nullable InteractionEnvironment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * Output only. The environment ID for the interaction. Only populated if environment
         * config is set in the request.
         */
        public Builder environmentId(@Nullable String environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /**
         * Output only. Diagnostic faults / platform errors recorded on the interaction.
         */
        public Builder errors(@Nullable List<Error> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Configuration parameters for model interactions.
         */
        public Builder generationConfig(@Nullable GenerationConfig generationConfig) {
            this.generationConfig = generationConfig;
            return this;
        }

        /**
         * Required. Output only. A unique identifier for the interaction completion.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /**
         * The input for the interaction.
         */
        public Builder input(@Nullable InteractionsInput input) {
            this.input = input;
            return this;
        }

        /**
         * The labels with user-defined metadata for the request.
         * 
         * <p>Label keys and values can be no longer than 63 characters
         * (Unicode codepoints) and can only contain lowercase letters, numeric
         * characters, underscores, and dashes. International characters are allowed.
         * Label values are optional. Label keys must start with a letter.
         */
        public Builder labels(@Nullable Map<String, String> labels) {
            this.labels = labels;
            return this;
        }

        /**
         * The model that will complete your prompt.\n\nSee
         * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
         */
        public Builder model(@Nullable Model model) {
            this.model = model;
            return this;
        }

        /**
         * An audio content block.
         */
        public Builder outputAudio(@Nullable AudioContent outputAudio) {
            this.outputAudio = outputAudio;
            return this;
        }

        /**
         * An image content block.
         */
        public Builder outputImage(@Nullable ImageContent outputImage) {
            this.outputImage = outputImage;
            return this;
        }

        /**
         * Concatenated text from the last model output in response to the current request.
         * 
         * <p>Note: this is added by the SDK.
         */
        public Builder outputText(@Nullable String outputText) {
            this.outputText = outputText;
            return this;
        }

        /**
         * A video content block.
         */
        public Builder outputVideo(@Nullable VideoContent outputVideo) {
            this.outputVideo = outputVideo;
            return this;
        }

        /**
         * The ID of the previous interaction, if any.
         */
        public Builder previousInteractionId(@Nullable String previousInteractionId) {
            this.previousInteractionId = previousInteractionId;
            return this;
        }

        /**
         * Enforces that the generated response is a JSON object that complies with
         * the JSON schema specified in this field.
         */
        public Builder responseFormat(@Nullable InteractionResponseFormat responseFormat) {
            this.responseFormat = responseFormat;
            return this;
        }

        /**
         * The mime type of the response. This is required if response_format is set.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder responseMimeType(@Nullable String responseMimeType) {
            this.responseMimeType = responseMimeType;
            return this;
        }

        /**
         * The requested modalities of the response (TEXT, IMAGE, AUDIO).
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder responseModalities(@Nullable List<ResponseModality> responseModalities) {
            this.responseModalities = responseModalities;
            return this;
        }

        /**
         * Safety settings for the interaction.
         */
        public Builder safetySettings(@Nullable List<SafetySetting> safetySettings) {
            this.safetySettings = safetySettings;
            return this;
        }

        public Builder serviceTier(@Nullable ServiceTier serviceTier) {
            this.serviceTier = serviceTier;
            return this;
        }

        /**
         * Required. Output only. The status of the interaction.
         */
        public Builder status(@Nonnull InteractionStatus status) {
            this.status = Utils.checkNotNull(status, "status");
            return this;
        }

        /**
         * Required. Output only. The steps that make up the interaction, when included in the response.
         */
        public Builder steps(@Nullable List<Step> steps) {
            this.steps = steps;
            return this;
        }

        /**
         * System instruction for the interaction.
         */
        public Builder systemInstruction(@Nullable String systemInstruction) {
            this.systemInstruction = systemInstruction;
            return this;
        }

        /**
         * A list of tool declarations the model may call during interaction.
         */
        public Builder tools(@Nullable List<Tool> tools) {
            this.tools = tools;
            return this;
        }

        /**
         * Required. Output only. The time at which the response was last updated in ISO 8601 format
         * (YYYY-MM-DDThh:mm:ssZ).
         */
        public Builder updated(@Nullable String updated) {
            this.updated = updated;
            return this;
        }

        /**
         * Statistics on the interaction request's token usage.
         */
        public Builder usage(@Nullable Usage usage) {
            this.usage = usage;
            return this;
        }

        /**
         * Message for configuring webhook events for a request.
         */
        public Builder webhookConfig(@Nullable WebhookConfig webhookConfig) {
            this.webhookConfig = webhookConfig;
            return this;
        }

        public Interaction build() {
            return new Interaction(
                agent, agentConfig, cachedContent,
                continuationToken, created, environment,
                environmentId, errors, generationConfig,
                id, input, labels,
                model, outputAudio, outputImage,
                outputText, outputVideo, previousInteractionId,
                responseFormat, responseMimeType, responseModalities,
                safetySettings, serviceTier, status,
                steps, systemInstruction, tools,
                updated, usage, webhookConfig);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Id =
                new LazySingletonValue<>(
                        "id",
                        "\"\"",
                        new TypeReference<String>() {});
    }
}
