/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * Model
 * 
 * <p>The model that will complete your prompt.\n\nSee
 * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
 */
public class Model {

    public static final Model GEMINI25_FLASH = new Model("gemini-2.5-flash");
    public static final Model GEMINI25_PRO = new Model("gemini-2.5-pro");
    public static final Model GEMMA426B_A4B_IT = new Model("gemma-4-26b-a4b-it");
    public static final Model GEMMA431B_IT = new Model("gemma-4-31b-it");
    public static final Model GEMINI_FLASH_LATEST = new Model("gemini-flash-latest");
    public static final Model GEMINI_FLASH_LITE_LATEST = new Model("gemini-flash-lite-latest");
    public static final Model GEMINI_PRO_LATEST = new Model("gemini-pro-latest");
    public static final Model GEMINI25_FLASH_LITE = new Model("gemini-2.5-flash-lite");
    public static final Model GEMINI25_FLASH_IMAGE = new Model("gemini-2.5-flash-image");
    public static final Model GEMINI3_FLASH_PREVIEW = new Model("gemini-3-flash-preview");
    public static final Model GEMINI31_PRO_PREVIEW = new Model("gemini-3.1-pro-preview");
    public static final Model GEMINI31_PRO_PREVIEW_CUSTOMTOOLS = new Model("gemini-3.1-pro-preview-customtools");
    public static final Model GEMINI31_FLASH_LITE = new Model("gemini-3.1-flash-lite");
    public static final Model GEMINI3_PRO_IMAGE = new Model("gemini-3-pro-image");
    public static final Model NANO_BANANA_PRO_PREVIEW = new Model("nano-banana-pro-preview");
    public static final Model GEMINI31_FLASH_IMAGE = new Model("gemini-3.1-flash-image");
    public static final Model GEMINI31_FLASH_TTS_PREVIEW = new Model("gemini-3.1-flash-tts-preview");
    public static final Model GEMINI35_FLASH = new Model("gemini-3.5-flash");
    public static final Model GEMINI36_FLASH = new Model("gemini-3.6-flash");
    public static final Model GEMINI37_FLASH = new Model("gemini-3.7-flash");
    public static final Model GEMINI38_FLASH = new Model("gemini-3.8-flash");
    public static final Model GEMINI38_FLASH_TTS = new Model("gemini-3.8-flash-tts");
    public static final Model GEMINI38_FLASH_LITE_TTS = new Model("gemini-3.8-flash-lite-tts");
    public static final Model LYRIA3_CLIP_PREVIEW = new Model("lyria-3-clip-preview");
    public static final Model LYRIA3_PRO_PREVIEW = new Model("lyria-3-pro-preview");
    public static final Model GEMINI_ROBOTICS_ER16_PREVIEW = new Model("gemini-robotics-er-1.6-preview");
    public static final Model GEMINI_ROBOTICS_ER2_PREVIEW = new Model("gemini-robotics-er-2-preview");
    public static final Model LYRIA35 = new Model("lyria-3.5");
    public static final Model GEMINI_OMNI11_FLASH = new Model("gemini-omni-1.1-flash");
    public static final Model GEMINI_OMNI_FLASH_PREVIEW = new Model("gemini-omni-flash-preview");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, Model> values = createValuesMap();
    private static final Map<String, ModelEnum> enums = createEnumsMap();

    private final String value;

    private Model(String value) {
        this.value = value;
    }

    /**
     * Returns a Model with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as Model
     */ 
    @JsonCreator
    public static Model of(String value) {
        synchronized (Model.class) {
            return values.computeIfAbsent(value, v -> new Model(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ModelEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Model other = (Model) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "Model [value=" + value + "]";
    }

    // return an array just like an enum
    public static Model[] values() {
        synchronized (Model.class) {
            return values.values().toArray(new Model[] {});
        }
    }

    private static final Map<String, Model> createValuesMap() {
        Map<String, Model> map = new LinkedHashMap<>();
        map.put("gemini-2.5-flash", GEMINI25_FLASH);
        map.put("gemini-2.5-pro", GEMINI25_PRO);
        map.put("gemma-4-26b-a4b-it", GEMMA426B_A4B_IT);
        map.put("gemma-4-31b-it", GEMMA431B_IT);
        map.put("gemini-flash-latest", GEMINI_FLASH_LATEST);
        map.put("gemini-flash-lite-latest", GEMINI_FLASH_LITE_LATEST);
        map.put("gemini-pro-latest", GEMINI_PRO_LATEST);
        map.put("gemini-2.5-flash-lite", GEMINI25_FLASH_LITE);
        map.put("gemini-2.5-flash-image", GEMINI25_FLASH_IMAGE);
        map.put("gemini-3-flash-preview", GEMINI3_FLASH_PREVIEW);
        map.put("gemini-3.1-pro-preview", GEMINI31_PRO_PREVIEW);
        map.put("gemini-3.1-pro-preview-customtools", GEMINI31_PRO_PREVIEW_CUSTOMTOOLS);
        map.put("gemini-3.1-flash-lite", GEMINI31_FLASH_LITE);
        map.put("gemini-3-pro-image", GEMINI3_PRO_IMAGE);
        map.put("nano-banana-pro-preview", NANO_BANANA_PRO_PREVIEW);
        map.put("gemini-3.1-flash-image", GEMINI31_FLASH_IMAGE);
        map.put("gemini-3.1-flash-tts-preview", GEMINI31_FLASH_TTS_PREVIEW);
        map.put("gemini-3.5-flash", GEMINI35_FLASH);
        map.put("gemini-3.6-flash", GEMINI36_FLASH);
        map.put("gemini-3.7-flash", GEMINI37_FLASH);
        map.put("gemini-3.8-flash", GEMINI38_FLASH);
        map.put("gemini-3.8-flash-tts", GEMINI38_FLASH_TTS);
        map.put("gemini-3.8-flash-lite-tts", GEMINI38_FLASH_LITE_TTS);
        map.put("lyria-3-clip-preview", LYRIA3_CLIP_PREVIEW);
        map.put("lyria-3-pro-preview", LYRIA3_PRO_PREVIEW);
        map.put("gemini-robotics-er-1.6-preview", GEMINI_ROBOTICS_ER16_PREVIEW);
        map.put("gemini-robotics-er-2-preview", GEMINI_ROBOTICS_ER2_PREVIEW);
        map.put("lyria-3.5", LYRIA35);
        map.put("gemini-omni-1.1-flash", GEMINI_OMNI11_FLASH);
        map.put("gemini-omni-flash-preview", GEMINI_OMNI_FLASH_PREVIEW);
        return map;
    }

    private static final Map<String, ModelEnum> createEnumsMap() {
        Map<String, ModelEnum> map = new HashMap<>();
        map.put("gemini-2.5-flash", ModelEnum.GEMINI25_FLASH);
        map.put("gemini-2.5-pro", ModelEnum.GEMINI25_PRO);
        map.put("gemma-4-26b-a4b-it", ModelEnum.GEMMA426B_A4B_IT);
        map.put("gemma-4-31b-it", ModelEnum.GEMMA431B_IT);
        map.put("gemini-flash-latest", ModelEnum.GEMINI_FLASH_LATEST);
        map.put("gemini-flash-lite-latest", ModelEnum.GEMINI_FLASH_LITE_LATEST);
        map.put("gemini-pro-latest", ModelEnum.GEMINI_PRO_LATEST);
        map.put("gemini-2.5-flash-lite", ModelEnum.GEMINI25_FLASH_LITE);
        map.put("gemini-2.5-flash-image", ModelEnum.GEMINI25_FLASH_IMAGE);
        map.put("gemini-3-flash-preview", ModelEnum.GEMINI3_FLASH_PREVIEW);
        map.put("gemini-3.1-pro-preview", ModelEnum.GEMINI31_PRO_PREVIEW);
        map.put("gemini-3.1-pro-preview-customtools", ModelEnum.GEMINI31_PRO_PREVIEW_CUSTOMTOOLS);
        map.put("gemini-3.1-flash-lite", ModelEnum.GEMINI31_FLASH_LITE);
        map.put("gemini-3-pro-image", ModelEnum.GEMINI3_PRO_IMAGE);
        map.put("nano-banana-pro-preview", ModelEnum.NANO_BANANA_PRO_PREVIEW);
        map.put("gemini-3.1-flash-image", ModelEnum.GEMINI31_FLASH_IMAGE);
        map.put("gemini-3.1-flash-tts-preview", ModelEnum.GEMINI31_FLASH_TTS_PREVIEW);
        map.put("gemini-3.5-flash", ModelEnum.GEMINI35_FLASH);
        map.put("gemini-3.6-flash", ModelEnum.GEMINI36_FLASH);
        map.put("gemini-3.7-flash", ModelEnum.GEMINI37_FLASH);
        map.put("gemini-3.8-flash", ModelEnum.GEMINI38_FLASH);
        map.put("gemini-3.8-flash-tts", ModelEnum.GEMINI38_FLASH_TTS);
        map.put("gemini-3.8-flash-lite-tts", ModelEnum.GEMINI38_FLASH_LITE_TTS);
        map.put("lyria-3-clip-preview", ModelEnum.LYRIA3_CLIP_PREVIEW);
        map.put("lyria-3-pro-preview", ModelEnum.LYRIA3_PRO_PREVIEW);
        map.put("gemini-robotics-er-1.6-preview", ModelEnum.GEMINI_ROBOTICS_ER16_PREVIEW);
        map.put("gemini-robotics-er-2-preview", ModelEnum.GEMINI_ROBOTICS_ER2_PREVIEW);
        map.put("lyria-3.5", ModelEnum.LYRIA35);
        map.put("gemini-omni-1.1-flash", ModelEnum.GEMINI_OMNI11_FLASH);
        map.put("gemini-omni-flash-preview", ModelEnum.GEMINI_OMNI_FLASH_PREVIEW);
        return map;
    }
    
    
    public enum ModelEnum {

        GEMINI25_FLASH("gemini-2.5-flash"),
        GEMINI25_PRO("gemini-2.5-pro"),
        GEMMA426B_A4B_IT("gemma-4-26b-a4b-it"),
        GEMMA431B_IT("gemma-4-31b-it"),
        GEMINI_FLASH_LATEST("gemini-flash-latest"),
        GEMINI_FLASH_LITE_LATEST("gemini-flash-lite-latest"),
        GEMINI_PRO_LATEST("gemini-pro-latest"),
        GEMINI25_FLASH_LITE("gemini-2.5-flash-lite"),
        GEMINI25_FLASH_IMAGE("gemini-2.5-flash-image"),
        GEMINI3_FLASH_PREVIEW("gemini-3-flash-preview"),
        GEMINI31_PRO_PREVIEW("gemini-3.1-pro-preview"),
        GEMINI31_PRO_PREVIEW_CUSTOMTOOLS("gemini-3.1-pro-preview-customtools"),
        GEMINI31_FLASH_LITE("gemini-3.1-flash-lite"),
        GEMINI3_PRO_IMAGE("gemini-3-pro-image"),
        NANO_BANANA_PRO_PREVIEW("nano-banana-pro-preview"),
        GEMINI31_FLASH_IMAGE("gemini-3.1-flash-image"),
        GEMINI31_FLASH_TTS_PREVIEW("gemini-3.1-flash-tts-preview"),
        GEMINI35_FLASH("gemini-3.5-flash"),
        GEMINI36_FLASH("gemini-3.6-flash"),
        GEMINI37_FLASH("gemini-3.7-flash"),
        GEMINI38_FLASH("gemini-3.8-flash"),
        GEMINI38_FLASH_TTS("gemini-3.8-flash-tts"),
        GEMINI38_FLASH_LITE_TTS("gemini-3.8-flash-lite-tts"),
        LYRIA3_CLIP_PREVIEW("lyria-3-clip-preview"),
        LYRIA3_PRO_PREVIEW("lyria-3-pro-preview"),
        GEMINI_ROBOTICS_ER16_PREVIEW("gemini-robotics-er-1.6-preview"),
        GEMINI_ROBOTICS_ER2_PREVIEW("gemini-robotics-er-2-preview"),
        LYRIA35("lyria-3.5"),
        GEMINI_OMNI11_FLASH("gemini-omni-1.1-flash"),
        GEMINI_OMNI_FLASH_PREVIEW("gemini-omni-flash-preview"),;

        private final String value;

        private ModelEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

